/**
 * generated by Xtext 2.13.0
 */
package io.typefox.xtext.langserver.example.myDsl.impl;

import io.typefox.xtext.langserver.example.myDsl.MyDslPackage;
import io.typefox.xtext.langserver.example.myDsl.based_on_entity_set_definition;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>based on entity set definition</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.impl.based_on_entity_set_definitionImpl#getBased_on_entity_set_definition_name_entity_set <em>Based on entity set definition name entity set</em>}</li>
 * </ul>
 *
 * @generated
 */
public class based_on_entity_set_definitionImpl extends MinimalEObjectImpl.Container implements based_on_entity_set_definition
{
  /**
   * The default value of the '{@link #getBased_on_entity_set_definition_name_entity_set() <em>Based on entity set definition name entity set</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBased_on_entity_set_definition_name_entity_set()
   * @generated
   * @ordered
   */
  protected static final String BASED_ON_ENTITY_SET_DEFINITION_NAME_ENTITY_SET_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getBased_on_entity_set_definition_name_entity_set() <em>Based on entity set definition name entity set</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBased_on_entity_set_definition_name_entity_set()
   * @generated
   * @ordered
   */
  protected String based_on_entity_set_definition_name_entity_set = BASED_ON_ENTITY_SET_DEFINITION_NAME_ENTITY_SET_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected based_on_entity_set_definitionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.BASED_ON_ENTITY_SET_DEFINITION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getBased_on_entity_set_definition_name_entity_set()
  {
    return based_on_entity_set_definition_name_entity_set;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setBased_on_entity_set_definition_name_entity_set(String newBased_on_entity_set_definition_name_entity_set)
  {
    String oldBased_on_entity_set_definition_name_entity_set = based_on_entity_set_definition_name_entity_set;
    based_on_entity_set_definition_name_entity_set = newBased_on_entity_set_definition_name_entity_set;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.BASED_ON_ENTITY_SET_DEFINITION__BASED_ON_ENTITY_SET_DEFINITION_NAME_ENTITY_SET, oldBased_on_entity_set_definition_name_entity_set, based_on_entity_set_definition_name_entity_set));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.BASED_ON_ENTITY_SET_DEFINITION__BASED_ON_ENTITY_SET_DEFINITION_NAME_ENTITY_SET:
        return getBased_on_entity_set_definition_name_entity_set();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.BASED_ON_ENTITY_SET_DEFINITION__BASED_ON_ENTITY_SET_DEFINITION_NAME_ENTITY_SET:
        setBased_on_entity_set_definition_name_entity_set((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.BASED_ON_ENTITY_SET_DEFINITION__BASED_ON_ENTITY_SET_DEFINITION_NAME_ENTITY_SET:
        setBased_on_entity_set_definition_name_entity_set(BASED_ON_ENTITY_SET_DEFINITION_NAME_ENTITY_SET_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.BASED_ON_ENTITY_SET_DEFINITION__BASED_ON_ENTITY_SET_DEFINITION_NAME_ENTITY_SET:
        return BASED_ON_ENTITY_SET_DEFINITION_NAME_ENTITY_SET_EDEFAULT == null ? based_on_entity_set_definition_name_entity_set != null : !BASED_ON_ENTITY_SET_DEFINITION_NAME_ENTITY_SET_EDEFAULT.equals(based_on_entity_set_definition_name_entity_set);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (based_on_entity_set_definition_name_entity_set: ");
    result.append(based_on_entity_set_definition_name_entity_set);
    result.append(')');
    return result.toString();
  }

} //based_on_entity_set_definitionImpl
