/**
 * generated by Xtext 2.13.0
 */
package io.typefox.xtext.langserver.example.myDsl.impl;

import io.typefox.xtext.langserver.example.myDsl.MyDslPackage;
import io.typefox.xtext.langserver.example.myDsl.batch_sync_policy_definition;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>batch sync policy definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class batch_sync_policy_definitionImpl extends sync_policy_definitionImpl implements batch_sync_policy_definition
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected batch_sync_policy_definitionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.BATCH_SYNC_POLICY_DEFINITION;
  }

} //batch_sync_policy_definitionImpl
