/**
 * generated by Xtext 2.13.0
 */
package io.typefox.xtext.langserver.example.myDsl.impl;

import io.typefox.xtext.langserver.example.myDsl.MyDslPackage;
import io.typefox.xtext.langserver.example.myDsl.dependencies_definition;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>dependencies definition</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.impl.dependencies_definitionImpl#getDependency_reference <em>Dependency reference</em>}</li>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.impl.dependencies_definitionImpl#getDependency_reference2 <em>Dependency reference2</em>}</li>
 * </ul>
 *
 * @generated
 */
public class dependencies_definitionImpl extends MinimalEObjectImpl.Container implements dependencies_definition
{
  /**
   * The default value of the '{@link #getDependency_reference() <em>Dependency reference</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDependency_reference()
   * @generated
   * @ordered
   */
  protected static final String DEPENDENCY_REFERENCE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDependency_reference() <em>Dependency reference</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDependency_reference()
   * @generated
   * @ordered
   */
  protected String dependency_reference = DEPENDENCY_REFERENCE_EDEFAULT;

  /**
   * The default value of the '{@link #getDependency_reference2() <em>Dependency reference2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDependency_reference2()
   * @generated
   * @ordered
   */
  protected static final String DEPENDENCY_REFERENCE2_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDependency_reference2() <em>Dependency reference2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDependency_reference2()
   * @generated
   * @ordered
   */
  protected String dependency_reference2 = DEPENDENCY_REFERENCE2_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected dependencies_definitionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.DEPENDENCIES_DEFINITION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getDependency_reference()
  {
    return dependency_reference;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setDependency_reference(String newDependency_reference)
  {
    String oldDependency_reference = dependency_reference;
    dependency_reference = newDependency_reference;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.DEPENDENCIES_DEFINITION__DEPENDENCY_REFERENCE, oldDependency_reference, dependency_reference));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getDependency_reference2()
  {
    return dependency_reference2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setDependency_reference2(String newDependency_reference2)
  {
    String oldDependency_reference2 = dependency_reference2;
    dependency_reference2 = newDependency_reference2;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.DEPENDENCIES_DEFINITION__DEPENDENCY_REFERENCE2, oldDependency_reference2, dependency_reference2));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.DEPENDENCIES_DEFINITION__DEPENDENCY_REFERENCE:
        return getDependency_reference();
      case MyDslPackage.DEPENDENCIES_DEFINITION__DEPENDENCY_REFERENCE2:
        return getDependency_reference2();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.DEPENDENCIES_DEFINITION__DEPENDENCY_REFERENCE:
        setDependency_reference((String)newValue);
        return;
      case MyDslPackage.DEPENDENCIES_DEFINITION__DEPENDENCY_REFERENCE2:
        setDependency_reference2((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.DEPENDENCIES_DEFINITION__DEPENDENCY_REFERENCE:
        setDependency_reference(DEPENDENCY_REFERENCE_EDEFAULT);
        return;
      case MyDslPackage.DEPENDENCIES_DEFINITION__DEPENDENCY_REFERENCE2:
        setDependency_reference2(DEPENDENCY_REFERENCE2_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.DEPENDENCIES_DEFINITION__DEPENDENCY_REFERENCE:
        return DEPENDENCY_REFERENCE_EDEFAULT == null ? dependency_reference != null : !DEPENDENCY_REFERENCE_EDEFAULT.equals(dependency_reference);
      case MyDslPackage.DEPENDENCIES_DEFINITION__DEPENDENCY_REFERENCE2:
        return DEPENDENCY_REFERENCE2_EDEFAULT == null ? dependency_reference2 != null : !DEPENDENCY_REFERENCE2_EDEFAULT.equals(dependency_reference2);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (dependency_reference: ");
    result.append(dependency_reference);
    result.append(", dependency_reference2: ");
    result.append(dependency_reference2);
    result.append(')');
    return result.toString();
  }

} //dependencies_definitionImpl
