/**
 * generated by Xtext 2.13.0
 */
package io.typefox.xtext.langserver.example.myDsl.impl;

import io.typefox.xtext.langserver.example.myDsl.MyDslPackage;
import io.typefox.xtext.langserver.example.myDsl.exclude_details_setting;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>exclude details setting</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.impl.exclude_details_settingImpl#getExclude_details_entity <em>Exclude details entity</em>}</li>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.impl.exclude_details_settingImpl#getExclude_details_entity2 <em>Exclude details entity2</em>}</li>
 * </ul>
 *
 * @generated
 */
public class exclude_details_settingImpl extends MinimalEObjectImpl.Container implements exclude_details_setting
{
  /**
   * The default value of the '{@link #getExclude_details_entity() <em>Exclude details entity</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getExclude_details_entity()
   * @generated
   * @ordered
   */
  protected static final String EXCLUDE_DETAILS_ENTITY_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getExclude_details_entity() <em>Exclude details entity</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getExclude_details_entity()
   * @generated
   * @ordered
   */
  protected String exclude_details_entity = EXCLUDE_DETAILS_ENTITY_EDEFAULT;

  /**
   * The default value of the '{@link #getExclude_details_entity2() <em>Exclude details entity2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getExclude_details_entity2()
   * @generated
   * @ordered
   */
  protected static final String EXCLUDE_DETAILS_ENTITY2_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getExclude_details_entity2() <em>Exclude details entity2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getExclude_details_entity2()
   * @generated
   * @ordered
   */
  protected String exclude_details_entity2 = EXCLUDE_DETAILS_ENTITY2_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected exclude_details_settingImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.EXCLUDE_DETAILS_SETTING;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getExclude_details_entity()
  {
    return exclude_details_entity;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setExclude_details_entity(String newExclude_details_entity)
  {
    String oldExclude_details_entity = exclude_details_entity;
    exclude_details_entity = newExclude_details_entity;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.EXCLUDE_DETAILS_SETTING__EXCLUDE_DETAILS_ENTITY, oldExclude_details_entity, exclude_details_entity));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getExclude_details_entity2()
  {
    return exclude_details_entity2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setExclude_details_entity2(String newExclude_details_entity2)
  {
    String oldExclude_details_entity2 = exclude_details_entity2;
    exclude_details_entity2 = newExclude_details_entity2;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.EXCLUDE_DETAILS_SETTING__EXCLUDE_DETAILS_ENTITY2, oldExclude_details_entity2, exclude_details_entity2));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.EXCLUDE_DETAILS_SETTING__EXCLUDE_DETAILS_ENTITY:
        return getExclude_details_entity();
      case MyDslPackage.EXCLUDE_DETAILS_SETTING__EXCLUDE_DETAILS_ENTITY2:
        return getExclude_details_entity2();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.EXCLUDE_DETAILS_SETTING__EXCLUDE_DETAILS_ENTITY:
        setExclude_details_entity((String)newValue);
        return;
      case MyDslPackage.EXCLUDE_DETAILS_SETTING__EXCLUDE_DETAILS_ENTITY2:
        setExclude_details_entity2((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.EXCLUDE_DETAILS_SETTING__EXCLUDE_DETAILS_ENTITY:
        setExclude_details_entity(EXCLUDE_DETAILS_ENTITY_EDEFAULT);
        return;
      case MyDslPackage.EXCLUDE_DETAILS_SETTING__EXCLUDE_DETAILS_ENTITY2:
        setExclude_details_entity2(EXCLUDE_DETAILS_ENTITY2_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.EXCLUDE_DETAILS_SETTING__EXCLUDE_DETAILS_ENTITY:
        return EXCLUDE_DETAILS_ENTITY_EDEFAULT == null ? exclude_details_entity != null : !EXCLUDE_DETAILS_ENTITY_EDEFAULT.equals(exclude_details_entity);
      case MyDslPackage.EXCLUDE_DETAILS_SETTING__EXCLUDE_DETAILS_ENTITY2:
        return EXCLUDE_DETAILS_ENTITY2_EDEFAULT == null ? exclude_details_entity2 != null : !EXCLUDE_DETAILS_ENTITY2_EDEFAULT.equals(exclude_details_entity2);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (exclude_details_entity: ");
    result.append(exclude_details_entity);
    result.append(", exclude_details_entity2: ");
    result.append(exclude_details_entity2);
    result.append(')');
    return result.toString();
  }

} //exclude_details_settingImpl
