/**
 * generated by Xtext 2.13.0
 */
package io.typefox.xtext.langserver.example.myDsl.impl;

import io.typefox.xtext.langserver.example.myDsl.MyDslPackage;
import io.typefox.xtext.langserver.example.myDsl.dynamic_component_dependency;
import io.typefox.xtext.langserver.example.myDsl.include_fragment;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>include fragment</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.impl.include_fragmentImpl#getDynamic_component_dependency <em>Dynamic component dependency</em>}</li>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.impl.include_fragmentImpl#getFragmentToIncludeName <em>Fragment To Include Name</em>}</li>
 * </ul>
 *
 * @generated
 */
public class include_fragmentImpl extends MainElementImpl implements include_fragment
{
  /**
   * The cached value of the '{@link #getDynamic_component_dependency() <em>Dynamic component dependency</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDynamic_component_dependency()
   * @generated
   * @ordered
   */
  protected dynamic_component_dependency dynamic_component_dependency;

  /**
   * The default value of the '{@link #getFragmentToIncludeName() <em>Fragment To Include Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFragmentToIncludeName()
   * @generated
   * @ordered
   */
  protected static final String FRAGMENT_TO_INCLUDE_NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getFragmentToIncludeName() <em>Fragment To Include Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFragmentToIncludeName()
   * @generated
   * @ordered
   */
  protected String fragmentToIncludeName = FRAGMENT_TO_INCLUDE_NAME_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected include_fragmentImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.INCLUDE_FRAGMENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public dynamic_component_dependency getDynamic_component_dependency()
  {
    return dynamic_component_dependency;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetDynamic_component_dependency(dynamic_component_dependency newDynamic_component_dependency, NotificationChain msgs)
  {
    dynamic_component_dependency oldDynamic_component_dependency = dynamic_component_dependency;
    dynamic_component_dependency = newDynamic_component_dependency;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.INCLUDE_FRAGMENT__DYNAMIC_COMPONENT_DEPENDENCY, oldDynamic_component_dependency, newDynamic_component_dependency);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setDynamic_component_dependency(dynamic_component_dependency newDynamic_component_dependency)
  {
    if (newDynamic_component_dependency != dynamic_component_dependency)
    {
      NotificationChain msgs = null;
      if (dynamic_component_dependency != null)
        msgs = ((InternalEObject)dynamic_component_dependency).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.INCLUDE_FRAGMENT__DYNAMIC_COMPONENT_DEPENDENCY, null, msgs);
      if (newDynamic_component_dependency != null)
        msgs = ((InternalEObject)newDynamic_component_dependency).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.INCLUDE_FRAGMENT__DYNAMIC_COMPONENT_DEPENDENCY, null, msgs);
      msgs = basicSetDynamic_component_dependency(newDynamic_component_dependency, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.INCLUDE_FRAGMENT__DYNAMIC_COMPONENT_DEPENDENCY, newDynamic_component_dependency, newDynamic_component_dependency));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getFragmentToIncludeName()
  {
    return fragmentToIncludeName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setFragmentToIncludeName(String newFragmentToIncludeName)
  {
    String oldFragmentToIncludeName = fragmentToIncludeName;
    fragmentToIncludeName = newFragmentToIncludeName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.INCLUDE_FRAGMENT__FRAGMENT_TO_INCLUDE_NAME, oldFragmentToIncludeName, fragmentToIncludeName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.INCLUDE_FRAGMENT__DYNAMIC_COMPONENT_DEPENDENCY:
        return basicSetDynamic_component_dependency(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.INCLUDE_FRAGMENT__DYNAMIC_COMPONENT_DEPENDENCY:
        return getDynamic_component_dependency();
      case MyDslPackage.INCLUDE_FRAGMENT__FRAGMENT_TO_INCLUDE_NAME:
        return getFragmentToIncludeName();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.INCLUDE_FRAGMENT__DYNAMIC_COMPONENT_DEPENDENCY:
        setDynamic_component_dependency((dynamic_component_dependency)newValue);
        return;
      case MyDslPackage.INCLUDE_FRAGMENT__FRAGMENT_TO_INCLUDE_NAME:
        setFragmentToIncludeName((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.INCLUDE_FRAGMENT__DYNAMIC_COMPONENT_DEPENDENCY:
        setDynamic_component_dependency((dynamic_component_dependency)null);
        return;
      case MyDslPackage.INCLUDE_FRAGMENT__FRAGMENT_TO_INCLUDE_NAME:
        setFragmentToIncludeName(FRAGMENT_TO_INCLUDE_NAME_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.INCLUDE_FRAGMENT__DYNAMIC_COMPONENT_DEPENDENCY:
        return dynamic_component_dependency != null;
      case MyDslPackage.INCLUDE_FRAGMENT__FRAGMENT_TO_INCLUDE_NAME:
        return FRAGMENT_TO_INCLUDE_NAME_EDEFAULT == null ? fragmentToIncludeName != null : !FRAGMENT_TO_INCLUDE_NAME_EDEFAULT.equals(fragmentToIncludeName);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (FragmentToIncludeName: ");
    result.append(fragmentToIncludeName);
    result.append(')');
    return result.toString();
  }

} //include_fragmentImpl
