/**
 * generated by Xtext 2.13.0
 */
package io.typefox.xtext.langserver.example.myDsl.impl;

import io.typefox.xtext.langserver.example.myDsl.MyDslPackage;
import io.typefox.xtext.langserver.example.myDsl.key_reference;
import io.typefox.xtext.langserver.example.myDsl.keys_definition;
import io.typefox.xtext.langserver.example.myDsl.where_definition;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>keys definition</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.impl.keys_definitionImpl#getKey_reference <em>Key reference</em>}</li>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.impl.keys_definitionImpl#getWhere_definition <em>Where definition</em>}</li>
 * </ul>
 *
 * @generated
 */
public class keys_definitionImpl extends MinimalEObjectImpl.Container implements keys_definition
{
  /**
   * The cached value of the '{@link #getKey_reference() <em>Key reference</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getKey_reference()
   * @generated
   * @ordered
   */
  protected key_reference key_reference;

  /**
   * The cached value of the '{@link #getWhere_definition() <em>Where definition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getWhere_definition()
   * @generated
   * @ordered
   */
  protected where_definition where_definition;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected keys_definitionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.KEYS_DEFINITION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public key_reference getKey_reference()
  {
    return key_reference;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetKey_reference(key_reference newKey_reference, NotificationChain msgs)
  {
    key_reference oldKey_reference = key_reference;
    key_reference = newKey_reference;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.KEYS_DEFINITION__KEY_REFERENCE, oldKey_reference, newKey_reference);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setKey_reference(key_reference newKey_reference)
  {
    if (newKey_reference != key_reference)
    {
      NotificationChain msgs = null;
      if (key_reference != null)
        msgs = ((InternalEObject)key_reference).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.KEYS_DEFINITION__KEY_REFERENCE, null, msgs);
      if (newKey_reference != null)
        msgs = ((InternalEObject)newKey_reference).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.KEYS_DEFINITION__KEY_REFERENCE, null, msgs);
      msgs = basicSetKey_reference(newKey_reference, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.KEYS_DEFINITION__KEY_REFERENCE, newKey_reference, newKey_reference));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public where_definition getWhere_definition()
  {
    return where_definition;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetWhere_definition(where_definition newWhere_definition, NotificationChain msgs)
  {
    where_definition oldWhere_definition = where_definition;
    where_definition = newWhere_definition;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.KEYS_DEFINITION__WHERE_DEFINITION, oldWhere_definition, newWhere_definition);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setWhere_definition(where_definition newWhere_definition)
  {
    if (newWhere_definition != where_definition)
    {
      NotificationChain msgs = null;
      if (where_definition != null)
        msgs = ((InternalEObject)where_definition).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.KEYS_DEFINITION__WHERE_DEFINITION, null, msgs);
      if (newWhere_definition != null)
        msgs = ((InternalEObject)newWhere_definition).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.KEYS_DEFINITION__WHERE_DEFINITION, null, msgs);
      msgs = basicSetWhere_definition(newWhere_definition, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.KEYS_DEFINITION__WHERE_DEFINITION, newWhere_definition, newWhere_definition));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.KEYS_DEFINITION__KEY_REFERENCE:
        return basicSetKey_reference(null, msgs);
      case MyDslPackage.KEYS_DEFINITION__WHERE_DEFINITION:
        return basicSetWhere_definition(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.KEYS_DEFINITION__KEY_REFERENCE:
        return getKey_reference();
      case MyDslPackage.KEYS_DEFINITION__WHERE_DEFINITION:
        return getWhere_definition();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.KEYS_DEFINITION__KEY_REFERENCE:
        setKey_reference((key_reference)newValue);
        return;
      case MyDslPackage.KEYS_DEFINITION__WHERE_DEFINITION:
        setWhere_definition((where_definition)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.KEYS_DEFINITION__KEY_REFERENCE:
        setKey_reference((key_reference)null);
        return;
      case MyDslPackage.KEYS_DEFINITION__WHERE_DEFINITION:
        setWhere_definition((where_definition)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.KEYS_DEFINITION__KEY_REFERENCE:
        return key_reference != null;
      case MyDslPackage.KEYS_DEFINITION__WHERE_DEFINITION:
        return where_definition != null;
    }
    return super.eIsSet(featureID);
  }

} //keys_definitionImpl
