/**
 * generated by Xtext 2.13.0
 */
package io.typefox.xtext.langserver.example.myDsl.impl;

import io.typefox.xtext.langserver.example.myDsl.MyDslPackage;
import io.typefox.xtext.langserver.example.myDsl.state_event_definition;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>state event definition</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.impl.state_event_definitionImpl#getState_event_definition_event_name <em>State event definition event name</em>}</li>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.impl.state_event_definitionImpl#getAlt <em>Alt</em>}</li>
 * </ul>
 *
 * @generated
 */
public class state_event_definitionImpl extends MinimalEObjectImpl.Container implements state_event_definition
{
  /**
   * The default value of the '{@link #getState_event_definition_event_name() <em>State event definition event name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getState_event_definition_event_name()
   * @generated
   * @ordered
   */
  protected static final String STATE_EVENT_DEFINITION_EVENT_NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getState_event_definition_event_name() <em>State event definition event name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getState_event_definition_event_name()
   * @generated
   * @ordered
   */
  protected String state_event_definition_event_name = STATE_EVENT_DEFINITION_EVENT_NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getAlt() <em>Alt</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAlt()
   * @generated
   * @ordered
   */
  protected EObject alt;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected state_event_definitionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.STATE_EVENT_DEFINITION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getState_event_definition_event_name()
  {
    return state_event_definition_event_name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setState_event_definition_event_name(String newState_event_definition_event_name)
  {
    String oldState_event_definition_event_name = state_event_definition_event_name;
    state_event_definition_event_name = newState_event_definition_event_name;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.STATE_EVENT_DEFINITION__STATE_EVENT_DEFINITION_EVENT_NAME, oldState_event_definition_event_name, state_event_definition_event_name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EObject getAlt()
  {
    return alt;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetAlt(EObject newAlt, NotificationChain msgs)
  {
    EObject oldAlt = alt;
    alt = newAlt;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.STATE_EVENT_DEFINITION__ALT, oldAlt, newAlt);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setAlt(EObject newAlt)
  {
    if (newAlt != alt)
    {
      NotificationChain msgs = null;
      if (alt != null)
        msgs = ((InternalEObject)alt).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.STATE_EVENT_DEFINITION__ALT, null, msgs);
      if (newAlt != null)
        msgs = ((InternalEObject)newAlt).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.STATE_EVENT_DEFINITION__ALT, null, msgs);
      msgs = basicSetAlt(newAlt, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.STATE_EVENT_DEFINITION__ALT, newAlt, newAlt));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.STATE_EVENT_DEFINITION__ALT:
        return basicSetAlt(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.STATE_EVENT_DEFINITION__STATE_EVENT_DEFINITION_EVENT_NAME:
        return getState_event_definition_event_name();
      case MyDslPackage.STATE_EVENT_DEFINITION__ALT:
        return getAlt();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.STATE_EVENT_DEFINITION__STATE_EVENT_DEFINITION_EVENT_NAME:
        setState_event_definition_event_name((String)newValue);
        return;
      case MyDslPackage.STATE_EVENT_DEFINITION__ALT:
        setAlt((EObject)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.STATE_EVENT_DEFINITION__STATE_EVENT_DEFINITION_EVENT_NAME:
        setState_event_definition_event_name(STATE_EVENT_DEFINITION_EVENT_NAME_EDEFAULT);
        return;
      case MyDslPackage.STATE_EVENT_DEFINITION__ALT:
        setAlt((EObject)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.STATE_EVENT_DEFINITION__STATE_EVENT_DEFINITION_EVENT_NAME:
        return STATE_EVENT_DEFINITION_EVENT_NAME_EDEFAULT == null ? state_event_definition_event_name != null : !STATE_EVENT_DEFINITION_EVENT_NAME_EDEFAULT.equals(state_event_definition_event_name);
      case MyDslPackage.STATE_EVENT_DEFINITION__ALT:
        return alt != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (state_event_definition_event_name: ");
    result.append(state_event_definition_event_name);
    result.append(')');
    return result.toString();
  }

} //state_event_definitionImpl
