/**
 * generated by Xtext 2.13.0
 */
package io.typefox.xtext.langserver.example.myDsl.impl;

import io.typefox.xtext.langserver.example.myDsl.MyDslPackage;
import io.typefox.xtext.langserver.example.myDsl.sync_group_definition;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>sync group definition</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.impl.sync_group_definitionImpl#getSync_group_definition_value <em>Sync group definition value</em>}</li>
 * </ul>
 *
 * @generated
 */
public class sync_group_definitionImpl extends MinimalEObjectImpl.Container implements sync_group_definition
{
  /**
   * The default value of the '{@link #getSync_group_definition_value() <em>Sync group definition value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSync_group_definition_value()
   * @generated
   * @ordered
   */
  protected static final String SYNC_GROUP_DEFINITION_VALUE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getSync_group_definition_value() <em>Sync group definition value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSync_group_definition_value()
   * @generated
   * @ordered
   */
  protected String sync_group_definition_value = SYNC_GROUP_DEFINITION_VALUE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected sync_group_definitionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.SYNC_GROUP_DEFINITION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getSync_group_definition_value()
  {
    return sync_group_definition_value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setSync_group_definition_value(String newSync_group_definition_value)
  {
    String oldSync_group_definition_value = sync_group_definition_value;
    sync_group_definition_value = newSync_group_definition_value;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.SYNC_GROUP_DEFINITION__SYNC_GROUP_DEFINITION_VALUE, oldSync_group_definition_value, sync_group_definition_value));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.SYNC_GROUP_DEFINITION__SYNC_GROUP_DEFINITION_VALUE:
        return getSync_group_definition_value();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.SYNC_GROUP_DEFINITION__SYNC_GROUP_DEFINITION_VALUE:
        setSync_group_definition_value((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.SYNC_GROUP_DEFINITION__SYNC_GROUP_DEFINITION_VALUE:
        setSync_group_definition_value(SYNC_GROUP_DEFINITION_VALUE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.SYNC_GROUP_DEFINITION__SYNC_GROUP_DEFINITION_VALUE:
        return SYNC_GROUP_DEFINITION_VALUE_EDEFAULT == null ? sync_group_definition_value != null : !SYNC_GROUP_DEFINITION_VALUE_EDEFAULT.equals(sync_group_definition_value);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (sync_group_definition_value: ");
    result.append(sync_group_definition_value);
    result.append(')');
    return result.toString();
  }

} //sync_group_definitionImpl
