/**
 * generated by Xtext 2.13.0
 */
package io.typefox.xtext.langserver.example.myDsl.impl;

import io.typefox.xtext.langserver.example.myDsl.MyDslPackage;
import io.typefox.xtext.langserver.example.myDsl.filter_columns_definition;
import io.typefox.xtext.langserver.example.myDsl.trigger_on_definition;
import io.typefox.xtext.langserver.example.myDsl.user_column_definition;
import io.typefox.xtext.langserver.example.myDsl.user_filter_definition;
import io.typefox.xtext.langserver.example.myDsl.view_filter_definition;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>user filter definition</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.impl.user_filter_definitionImpl#getUser_filter_definition_filter_name <em>User filter definition filter name</em>}</li>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.impl.user_filter_definitionImpl#getView_filter_definition <em>View filter definition</em>}</li>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.impl.user_filter_definitionImpl#getUser_column_definition <em>User column definition</em>}</li>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.impl.user_filter_definitionImpl#getFilter_columns_definition <em>Filter columns definition</em>}</li>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.impl.user_filter_definitionImpl#getTrigger_on_definition <em>Trigger on definition</em>}</li>
 * </ul>
 *
 * @generated
 */
public class user_filter_definitionImpl extends MainElementImpl implements user_filter_definition
{
  /**
   * The default value of the '{@link #getUser_filter_definition_filter_name() <em>User filter definition filter name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUser_filter_definition_filter_name()
   * @generated
   * @ordered
   */
  protected static final String USER_FILTER_DEFINITION_FILTER_NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getUser_filter_definition_filter_name() <em>User filter definition filter name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUser_filter_definition_filter_name()
   * @generated
   * @ordered
   */
  protected String user_filter_definition_filter_name = USER_FILTER_DEFINITION_FILTER_NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getView_filter_definition() <em>View filter definition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getView_filter_definition()
   * @generated
   * @ordered
   */
  protected view_filter_definition view_filter_definition;

  /**
   * The cached value of the '{@link #getUser_column_definition() <em>User column definition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUser_column_definition()
   * @generated
   * @ordered
   */
  protected user_column_definition user_column_definition;

  /**
   * The cached value of the '{@link #getFilter_columns_definition() <em>Filter columns definition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFilter_columns_definition()
   * @generated
   * @ordered
   */
  protected filter_columns_definition filter_columns_definition;

  /**
   * The cached value of the '{@link #getTrigger_on_definition() <em>Trigger on definition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTrigger_on_definition()
   * @generated
   * @ordered
   */
  protected trigger_on_definition trigger_on_definition;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected user_filter_definitionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.USER_FILTER_DEFINITION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getUser_filter_definition_filter_name()
  {
    return user_filter_definition_filter_name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setUser_filter_definition_filter_name(String newUser_filter_definition_filter_name)
  {
    String oldUser_filter_definition_filter_name = user_filter_definition_filter_name;
    user_filter_definition_filter_name = newUser_filter_definition_filter_name;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.USER_FILTER_DEFINITION__USER_FILTER_DEFINITION_FILTER_NAME, oldUser_filter_definition_filter_name, user_filter_definition_filter_name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public view_filter_definition getView_filter_definition()
  {
    return view_filter_definition;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetView_filter_definition(view_filter_definition newView_filter_definition, NotificationChain msgs)
  {
    view_filter_definition oldView_filter_definition = view_filter_definition;
    view_filter_definition = newView_filter_definition;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.USER_FILTER_DEFINITION__VIEW_FILTER_DEFINITION, oldView_filter_definition, newView_filter_definition);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setView_filter_definition(view_filter_definition newView_filter_definition)
  {
    if (newView_filter_definition != view_filter_definition)
    {
      NotificationChain msgs = null;
      if (view_filter_definition != null)
        msgs = ((InternalEObject)view_filter_definition).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.USER_FILTER_DEFINITION__VIEW_FILTER_DEFINITION, null, msgs);
      if (newView_filter_definition != null)
        msgs = ((InternalEObject)newView_filter_definition).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.USER_FILTER_DEFINITION__VIEW_FILTER_DEFINITION, null, msgs);
      msgs = basicSetView_filter_definition(newView_filter_definition, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.USER_FILTER_DEFINITION__VIEW_FILTER_DEFINITION, newView_filter_definition, newView_filter_definition));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public user_column_definition getUser_column_definition()
  {
    return user_column_definition;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetUser_column_definition(user_column_definition newUser_column_definition, NotificationChain msgs)
  {
    user_column_definition oldUser_column_definition = user_column_definition;
    user_column_definition = newUser_column_definition;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.USER_FILTER_DEFINITION__USER_COLUMN_DEFINITION, oldUser_column_definition, newUser_column_definition);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setUser_column_definition(user_column_definition newUser_column_definition)
  {
    if (newUser_column_definition != user_column_definition)
    {
      NotificationChain msgs = null;
      if (user_column_definition != null)
        msgs = ((InternalEObject)user_column_definition).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.USER_FILTER_DEFINITION__USER_COLUMN_DEFINITION, null, msgs);
      if (newUser_column_definition != null)
        msgs = ((InternalEObject)newUser_column_definition).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.USER_FILTER_DEFINITION__USER_COLUMN_DEFINITION, null, msgs);
      msgs = basicSetUser_column_definition(newUser_column_definition, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.USER_FILTER_DEFINITION__USER_COLUMN_DEFINITION, newUser_column_definition, newUser_column_definition));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public filter_columns_definition getFilter_columns_definition()
  {
    return filter_columns_definition;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetFilter_columns_definition(filter_columns_definition newFilter_columns_definition, NotificationChain msgs)
  {
    filter_columns_definition oldFilter_columns_definition = filter_columns_definition;
    filter_columns_definition = newFilter_columns_definition;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.USER_FILTER_DEFINITION__FILTER_COLUMNS_DEFINITION, oldFilter_columns_definition, newFilter_columns_definition);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setFilter_columns_definition(filter_columns_definition newFilter_columns_definition)
  {
    if (newFilter_columns_definition != filter_columns_definition)
    {
      NotificationChain msgs = null;
      if (filter_columns_definition != null)
        msgs = ((InternalEObject)filter_columns_definition).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.USER_FILTER_DEFINITION__FILTER_COLUMNS_DEFINITION, null, msgs);
      if (newFilter_columns_definition != null)
        msgs = ((InternalEObject)newFilter_columns_definition).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.USER_FILTER_DEFINITION__FILTER_COLUMNS_DEFINITION, null, msgs);
      msgs = basicSetFilter_columns_definition(newFilter_columns_definition, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.USER_FILTER_DEFINITION__FILTER_COLUMNS_DEFINITION, newFilter_columns_definition, newFilter_columns_definition));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public trigger_on_definition getTrigger_on_definition()
  {
    return trigger_on_definition;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetTrigger_on_definition(trigger_on_definition newTrigger_on_definition, NotificationChain msgs)
  {
    trigger_on_definition oldTrigger_on_definition = trigger_on_definition;
    trigger_on_definition = newTrigger_on_definition;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.USER_FILTER_DEFINITION__TRIGGER_ON_DEFINITION, oldTrigger_on_definition, newTrigger_on_definition);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setTrigger_on_definition(trigger_on_definition newTrigger_on_definition)
  {
    if (newTrigger_on_definition != trigger_on_definition)
    {
      NotificationChain msgs = null;
      if (trigger_on_definition != null)
        msgs = ((InternalEObject)trigger_on_definition).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.USER_FILTER_DEFINITION__TRIGGER_ON_DEFINITION, null, msgs);
      if (newTrigger_on_definition != null)
        msgs = ((InternalEObject)newTrigger_on_definition).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.USER_FILTER_DEFINITION__TRIGGER_ON_DEFINITION, null, msgs);
      msgs = basicSetTrigger_on_definition(newTrigger_on_definition, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.USER_FILTER_DEFINITION__TRIGGER_ON_DEFINITION, newTrigger_on_definition, newTrigger_on_definition));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.USER_FILTER_DEFINITION__VIEW_FILTER_DEFINITION:
        return basicSetView_filter_definition(null, msgs);
      case MyDslPackage.USER_FILTER_DEFINITION__USER_COLUMN_DEFINITION:
        return basicSetUser_column_definition(null, msgs);
      case MyDslPackage.USER_FILTER_DEFINITION__FILTER_COLUMNS_DEFINITION:
        return basicSetFilter_columns_definition(null, msgs);
      case MyDslPackage.USER_FILTER_DEFINITION__TRIGGER_ON_DEFINITION:
        return basicSetTrigger_on_definition(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.USER_FILTER_DEFINITION__USER_FILTER_DEFINITION_FILTER_NAME:
        return getUser_filter_definition_filter_name();
      case MyDslPackage.USER_FILTER_DEFINITION__VIEW_FILTER_DEFINITION:
        return getView_filter_definition();
      case MyDslPackage.USER_FILTER_DEFINITION__USER_COLUMN_DEFINITION:
        return getUser_column_definition();
      case MyDslPackage.USER_FILTER_DEFINITION__FILTER_COLUMNS_DEFINITION:
        return getFilter_columns_definition();
      case MyDslPackage.USER_FILTER_DEFINITION__TRIGGER_ON_DEFINITION:
        return getTrigger_on_definition();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.USER_FILTER_DEFINITION__USER_FILTER_DEFINITION_FILTER_NAME:
        setUser_filter_definition_filter_name((String)newValue);
        return;
      case MyDslPackage.USER_FILTER_DEFINITION__VIEW_FILTER_DEFINITION:
        setView_filter_definition((view_filter_definition)newValue);
        return;
      case MyDslPackage.USER_FILTER_DEFINITION__USER_COLUMN_DEFINITION:
        setUser_column_definition((user_column_definition)newValue);
        return;
      case MyDslPackage.USER_FILTER_DEFINITION__FILTER_COLUMNS_DEFINITION:
        setFilter_columns_definition((filter_columns_definition)newValue);
        return;
      case MyDslPackage.USER_FILTER_DEFINITION__TRIGGER_ON_DEFINITION:
        setTrigger_on_definition((trigger_on_definition)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.USER_FILTER_DEFINITION__USER_FILTER_DEFINITION_FILTER_NAME:
        setUser_filter_definition_filter_name(USER_FILTER_DEFINITION_FILTER_NAME_EDEFAULT);
        return;
      case MyDslPackage.USER_FILTER_DEFINITION__VIEW_FILTER_DEFINITION:
        setView_filter_definition((view_filter_definition)null);
        return;
      case MyDslPackage.USER_FILTER_DEFINITION__USER_COLUMN_DEFINITION:
        setUser_column_definition((user_column_definition)null);
        return;
      case MyDslPackage.USER_FILTER_DEFINITION__FILTER_COLUMNS_DEFINITION:
        setFilter_columns_definition((filter_columns_definition)null);
        return;
      case MyDslPackage.USER_FILTER_DEFINITION__TRIGGER_ON_DEFINITION:
        setTrigger_on_definition((trigger_on_definition)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.USER_FILTER_DEFINITION__USER_FILTER_DEFINITION_FILTER_NAME:
        return USER_FILTER_DEFINITION_FILTER_NAME_EDEFAULT == null ? user_filter_definition_filter_name != null : !USER_FILTER_DEFINITION_FILTER_NAME_EDEFAULT.equals(user_filter_definition_filter_name);
      case MyDslPackage.USER_FILTER_DEFINITION__VIEW_FILTER_DEFINITION:
        return view_filter_definition != null;
      case MyDslPackage.USER_FILTER_DEFINITION__USER_COLUMN_DEFINITION:
        return user_column_definition != null;
      case MyDslPackage.USER_FILTER_DEFINITION__FILTER_COLUMNS_DEFINITION:
        return filter_columns_definition != null;
      case MyDslPackage.USER_FILTER_DEFINITION__TRIGGER_ON_DEFINITION:
        return trigger_on_definition != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (user_filter_definition_filter_name: ");
    result.append(user_filter_definition_filter_name);
    result.append(')');
    return result.toString();
  }

} //user_filter_definitionImpl
