/**
 * generated by Xtext 2.13.0
 */
package io.typefox.xtext.langserver.example.myDsl.impl;

import io.typefox.xtext.langserver.example.myDsl.MyDslPackage;
import io.typefox.xtext.langserver.example.myDsl.projection_flag_condition;
import io.typefox.xtext.langserver.example.myDsl.validation_definition;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>validation definition</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.impl.validation_definitionImpl#getProjection_flag_condition <em>Projection flag condition</em>}</li>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.impl.validation_definitionImpl#getString <em>String</em>}</li>
 * </ul>
 *
 * @generated
 */
public class validation_definitionImpl extends MinimalEObjectImpl.Container implements validation_definition
{
  /**
   * The cached value of the '{@link #getProjection_flag_condition() <em>Projection flag condition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getProjection_flag_condition()
   * @generated
   * @ordered
   */
  protected projection_flag_condition projection_flag_condition;

  /**
   * The default value of the '{@link #getString() <em>String</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getString()
   * @generated
   * @ordered
   */
  protected static final String STRING_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getString() <em>String</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getString()
   * @generated
   * @ordered
   */
  protected String string = STRING_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected validation_definitionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.VALIDATION_DEFINITION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public projection_flag_condition getProjection_flag_condition()
  {
    return projection_flag_condition;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetProjection_flag_condition(projection_flag_condition newProjection_flag_condition, NotificationChain msgs)
  {
    projection_flag_condition oldProjection_flag_condition = projection_flag_condition;
    projection_flag_condition = newProjection_flag_condition;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.VALIDATION_DEFINITION__PROJECTION_FLAG_CONDITION, oldProjection_flag_condition, newProjection_flag_condition);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setProjection_flag_condition(projection_flag_condition newProjection_flag_condition)
  {
    if (newProjection_flag_condition != projection_flag_condition)
    {
      NotificationChain msgs = null;
      if (projection_flag_condition != null)
        msgs = ((InternalEObject)projection_flag_condition).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.VALIDATION_DEFINITION__PROJECTION_FLAG_CONDITION, null, msgs);
      if (newProjection_flag_condition != null)
        msgs = ((InternalEObject)newProjection_flag_condition).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.VALIDATION_DEFINITION__PROJECTION_FLAG_CONDITION, null, msgs);
      msgs = basicSetProjection_flag_condition(newProjection_flag_condition, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.VALIDATION_DEFINITION__PROJECTION_FLAG_CONDITION, newProjection_flag_condition, newProjection_flag_condition));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getString()
  {
    return string;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setString(String newString)
  {
    String oldString = string;
    string = newString;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.VALIDATION_DEFINITION__STRING, oldString, string));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.VALIDATION_DEFINITION__PROJECTION_FLAG_CONDITION:
        return basicSetProjection_flag_condition(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.VALIDATION_DEFINITION__PROJECTION_FLAG_CONDITION:
        return getProjection_flag_condition();
      case MyDslPackage.VALIDATION_DEFINITION__STRING:
        return getString();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.VALIDATION_DEFINITION__PROJECTION_FLAG_CONDITION:
        setProjection_flag_condition((projection_flag_condition)newValue);
        return;
      case MyDslPackage.VALIDATION_DEFINITION__STRING:
        setString((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.VALIDATION_DEFINITION__PROJECTION_FLAG_CONDITION:
        setProjection_flag_condition((projection_flag_condition)null);
        return;
      case MyDslPackage.VALIDATION_DEFINITION__STRING:
        setString(STRING_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.VALIDATION_DEFINITION__PROJECTION_FLAG_CONDITION:
        return projection_flag_condition != null;
      case MyDslPackage.VALIDATION_DEFINITION__STRING:
        return STRING_EDEFAULT == null ? string != null : !STRING_EDEFAULT.equals(string);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (string: ");
    result.append(string);
    result.append(')');
    return result.toString();
  }

} //validation_definitionImpl
