/**
 * generated by Xtext 2.13.0
 */
package io.typefox.xtext.langserver.example.myDsl.impl;

import io.typefox.xtext.langserver.example.myDsl.MyDslPackage;
import io.typefox.xtext.langserver.example.myDsl.view_filter_definition;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>view filter definition</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.impl.view_filter_definitionImpl#getView_filter_definition_view_name <em>View filter definition view name</em>}</li>
 * </ul>
 *
 * @generated
 */
public class view_filter_definitionImpl extends MinimalEObjectImpl.Container implements view_filter_definition
{
  /**
   * The default value of the '{@link #getView_filter_definition_view_name() <em>View filter definition view name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getView_filter_definition_view_name()
   * @generated
   * @ordered
   */
  protected static final String VIEW_FILTER_DEFINITION_VIEW_NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getView_filter_definition_view_name() <em>View filter definition view name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getView_filter_definition_view_name()
   * @generated
   * @ordered
   */
  protected String view_filter_definition_view_name = VIEW_FILTER_DEFINITION_VIEW_NAME_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected view_filter_definitionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.VIEW_FILTER_DEFINITION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getView_filter_definition_view_name()
  {
    return view_filter_definition_view_name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setView_filter_definition_view_name(String newView_filter_definition_view_name)
  {
    String oldView_filter_definition_view_name = view_filter_definition_view_name;
    view_filter_definition_view_name = newView_filter_definition_view_name;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.VIEW_FILTER_DEFINITION__VIEW_FILTER_DEFINITION_VIEW_NAME, oldView_filter_definition_view_name, view_filter_definition_view_name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.VIEW_FILTER_DEFINITION__VIEW_FILTER_DEFINITION_VIEW_NAME:
        return getView_filter_definition_view_name();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.VIEW_FILTER_DEFINITION__VIEW_FILTER_DEFINITION_VIEW_NAME:
        setView_filter_definition_view_name((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.VIEW_FILTER_DEFINITION__VIEW_FILTER_DEFINITION_VIEW_NAME:
        setView_filter_definition_view_name(VIEW_FILTER_DEFINITION_VIEW_NAME_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.VIEW_FILTER_DEFINITION__VIEW_FILTER_DEFINITION_VIEW_NAME:
        return VIEW_FILTER_DEFINITION_VIEW_NAME_EDEFAULT == null ? view_filter_definition_view_name != null : !VIEW_FILTER_DEFINITION_VIEW_NAME_EDEFAULT.equals(view_filter_definition_view_name);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (view_filter_definition_view_name: ");
    result.append(view_filter_definition_view_name);
    result.append(')');
    return result.toString();
  }

} //view_filter_definitionImpl
