/**
 * generated by Xtext 2.13.0
 */
package io.typefox.xtext.langserver.example.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>aggregate wildcard definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.aggregate_wildcard_definition#getAggregate_wildcard_definition_wildcard_token <em>Aggregate wildcard definition wildcard token</em>}</li>
 * </ul>
 *
 * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#getaggregate_wildcard_definition()
 * @model
 * @generated
 */
public interface aggregate_wildcard_definition extends EObject
{
  /**
   * Returns the value of the '<em><b>Aggregate wildcard definition wildcard token</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Aggregate wildcard definition wildcard token</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Aggregate wildcard definition wildcard token</em>' attribute.
   * @see #setAggregate_wildcard_definition_wildcard_token(String)
   * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#getaggregate_wildcard_definition_Aggregate_wildcard_definition_wildcard_token()
   * @model
   * @generated
   */
  String getAggregate_wildcard_definition_wildcard_token();

  /**
   * Sets the value of the '{@link io.typefox.xtext.langserver.example.myDsl.aggregate_wildcard_definition#getAggregate_wildcard_definition_wildcard_token <em>Aggregate wildcard definition wildcard token</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Aggregate wildcard definition wildcard token</em>' attribute.
   * @see #getAggregate_wildcard_definition_wildcard_token()
   * @generated
   */
  void setAggregate_wildcard_definition_wildcard_token(String value);

} // aggregate_wildcard_definition
