/**
 * generated by Xtext 2.13.0
 */
package io.typefox.xtext.langserver.example.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>array definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.array_definition#getDynamic_component_dependency <em>Dynamic component dependency</em>}</li>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.array_definition#getArray_definition_array_name <em>Array definition array name</em>}</li>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.array_definition#getKey_reference <em>Key reference</em>}</li>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.array_definition#getKey_reference2 <em>Key reference2</em>}</li>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.array_definition#getTo_reference_definition <em>To reference definition</em>}</li>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.array_definition#getWhere_definition <em>Where definition</em>}</li>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.array_definition#getFiltering_context_definition <em>Filtering context definition</em>}</li>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.array_definition#getOffline_filter_definition <em>Offline filter definition</em>}</li>
 * </ul>
 *
 * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#getarray_definition()
 * @model
 * @generated
 */
public interface array_definition extends EObject
{
  /**
   * Returns the value of the '<em><b>Dynamic component dependency</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Dynamic component dependency</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dynamic component dependency</em>' containment reference.
   * @see #setDynamic_component_dependency(dynamic_component_dependency)
   * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#getarray_definition_Dynamic_component_dependency()
   * @model containment="true"
   * @generated
   */
  dynamic_component_dependency getDynamic_component_dependency();

  /**
   * Sets the value of the '{@link io.typefox.xtext.langserver.example.myDsl.array_definition#getDynamic_component_dependency <em>Dynamic component dependency</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dynamic component dependency</em>' containment reference.
   * @see #getDynamic_component_dependency()
   * @generated
   */
  void setDynamic_component_dependency(dynamic_component_dependency value);

  /**
   * Returns the value of the '<em><b>Array definition array name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Array definition array name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Array definition array name</em>' attribute.
   * @see #setArray_definition_array_name(String)
   * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#getarray_definition_Array_definition_array_name()
   * @model
   * @generated
   */
  String getArray_definition_array_name();

  /**
   * Sets the value of the '{@link io.typefox.xtext.langserver.example.myDsl.array_definition#getArray_definition_array_name <em>Array definition array name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Array definition array name</em>' attribute.
   * @see #getArray_definition_array_name()
   * @generated
   */
  void setArray_definition_array_name(String value);

  /**
   * Returns the value of the '<em><b>Key reference</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Key reference</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Key reference</em>' containment reference.
   * @see #setKey_reference(key_reference)
   * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#getarray_definition_Key_reference()
   * @model containment="true"
   * @generated
   */
  key_reference getKey_reference();

  /**
   * Sets the value of the '{@link io.typefox.xtext.langserver.example.myDsl.array_definition#getKey_reference <em>Key reference</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Key reference</em>' containment reference.
   * @see #getKey_reference()
   * @generated
   */
  void setKey_reference(key_reference value);

  /**
   * Returns the value of the '<em><b>Key reference2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Key reference2</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Key reference2</em>' containment reference.
   * @see #setKey_reference2(key_reference)
   * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#getarray_definition_Key_reference2()
   * @model containment="true"
   * @generated
   */
  key_reference getKey_reference2();

  /**
   * Sets the value of the '{@link io.typefox.xtext.langserver.example.myDsl.array_definition#getKey_reference2 <em>Key reference2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Key reference2</em>' containment reference.
   * @see #getKey_reference2()
   * @generated
   */
  void setKey_reference2(key_reference value);

  /**
   * Returns the value of the '<em><b>To reference definition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>To reference definition</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>To reference definition</em>' containment reference.
   * @see #setTo_reference_definition(to_reference_definition)
   * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#getarray_definition_To_reference_definition()
   * @model containment="true"
   * @generated
   */
  to_reference_definition getTo_reference_definition();

  /**
   * Sets the value of the '{@link io.typefox.xtext.langserver.example.myDsl.array_definition#getTo_reference_definition <em>To reference definition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>To reference definition</em>' containment reference.
   * @see #getTo_reference_definition()
   * @generated
   */
  void setTo_reference_definition(to_reference_definition value);

  /**
   * Returns the value of the '<em><b>Where definition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Where definition</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Where definition</em>' containment reference.
   * @see #setWhere_definition(where_definition)
   * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#getarray_definition_Where_definition()
   * @model containment="true"
   * @generated
   */
  where_definition getWhere_definition();

  /**
   * Sets the value of the '{@link io.typefox.xtext.langserver.example.myDsl.array_definition#getWhere_definition <em>Where definition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Where definition</em>' containment reference.
   * @see #getWhere_definition()
   * @generated
   */
  void setWhere_definition(where_definition value);

  /**
   * Returns the value of the '<em><b>Filtering context definition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Filtering context definition</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Filtering context definition</em>' containment reference.
   * @see #setFiltering_context_definition(filtering_context_definition)
   * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#getarray_definition_Filtering_context_definition()
   * @model containment="true"
   * @generated
   */
  filtering_context_definition getFiltering_context_definition();

  /**
   * Sets the value of the '{@link io.typefox.xtext.langserver.example.myDsl.array_definition#getFiltering_context_definition <em>Filtering context definition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Filtering context definition</em>' containment reference.
   * @see #getFiltering_context_definition()
   * @generated
   */
  void setFiltering_context_definition(filtering_context_definition value);

  /**
   * Returns the value of the '<em><b>Offline filter definition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Offline filter definition</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Offline filter definition</em>' containment reference.
   * @see #setOffline_filter_definition(offline_filter_definition)
   * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#getarray_definition_Offline_filter_definition()
   * @model containment="true"
   * @generated
   */
  offline_filter_definition getOffline_filter_definition();

  /**
   * Sets the value of the '{@link io.typefox.xtext.langserver.example.myDsl.array_definition#getOffline_filter_definition <em>Offline filter definition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Offline filter definition</em>' containment reference.
   * @see #getOffline_filter_definition()
   * @generated
   */
  void setOffline_filter_definition(offline_filter_definition value);

} // array_definition
