/**
 * generated by Xtext 2.13.0
 */
package io.typefox.xtext.langserver.example.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>batch sync policy definition</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#getbatch_sync_policy_definition()
 * @model
 * @generated
 */
public interface batch_sync_policy_definition extends sync_policy_definition
{
} // batch_sync_policy_definition
