/**
 * generated by Xtext 2.13.0
 */
package io.typefox.xtext.langserver.example.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>combine attribute</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.combine_attribute#getTrigger_attribute <em>Trigger attribute</em>}</li>
 * </ul>
 *
 * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#getcombine_attribute()
 * @model
 * @generated
 */
public interface combine_attribute extends EObject
{
  /**
   * Returns the value of the '<em><b>Trigger attribute</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Trigger attribute</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Trigger attribute</em>' containment reference.
   * @see #setTrigger_attribute(trigger_attribute)
   * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#getcombine_attribute_Trigger_attribute()
   * @model containment="true"
   * @generated
   */
  trigger_attribute getTrigger_attribute();

  /**
   * Sets the value of the '{@link io.typefox.xtext.langserver.example.myDsl.combine_attribute#getTrigger_attribute <em>Trigger attribute</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Trigger attribute</em>' containment reference.
   * @see #getTrigger_attribute()
   * @generated
   */
  void setTrigger_attribute(trigger_attribute value);

} // combine_attribute
