/**
 * generated by Xtext 2.13.0
 */
package io.typefox.xtext.langserver.example.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>copy definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.copy_definition#getDataitem_reference <em>Dataitem reference</em>}</li>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.copy_definition#getCopy_definition_copy_name <em>Copy definition copy name</em>}</li>
 * </ul>
 *
 * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#getcopy_definition()
 * @model
 * @generated
 */
public interface copy_definition extends EObject
{
  /**
   * Returns the value of the '<em><b>Dataitem reference</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Dataitem reference</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dataitem reference</em>' containment reference.
   * @see #setDataitem_reference(dataitem_reference)
   * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#getcopy_definition_Dataitem_reference()
   * @model containment="true"
   * @generated
   */
  dataitem_reference getDataitem_reference();

  /**
   * Sets the value of the '{@link io.typefox.xtext.langserver.example.myDsl.copy_definition#getDataitem_reference <em>Dataitem reference</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dataitem reference</em>' containment reference.
   * @see #getDataitem_reference()
   * @generated
   */
  void setDataitem_reference(dataitem_reference value);

  /**
   * Returns the value of the '<em><b>Copy definition copy name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Copy definition copy name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Copy definition copy name</em>' attribute.
   * @see #setCopy_definition_copy_name(String)
   * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#getcopy_definition_Copy_definition_copy_name()
   * @model
   * @generated
   */
  String getCopy_definition_copy_name();

  /**
   * Sets the value of the '{@link io.typefox.xtext.langserver.example.myDsl.copy_definition#getCopy_definition_copy_name <em>Copy definition copy name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Copy definition copy name</em>' attribute.
   * @see #getCopy_definition_copy_name()
   * @generated
   */
  void setCopy_definition_copy_name(String value);

} // copy_definition
