/**
 * generated by Xtext 2.13.0
 */
package io.typefox.xtext.langserver.example.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>dataitem reference</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.dataitem_reference#getDataitem_reference_item_name <em>Dataitem reference item name</em>}</li>
 * </ul>
 *
 * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#getdataitem_reference()
 * @model
 * @generated
 */
public interface dataitem_reference extends EObject
{
  /**
   * Returns the value of the '<em><b>Dataitem reference item name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Dataitem reference item name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dataitem reference item name</em>' attribute.
   * @see #setDataitem_reference_item_name(String)
   * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#getdataitem_reference_Dataitem_reference_item_name()
   * @model
   * @generated
   */
  String getDataitem_reference_item_name();

  /**
   * Sets the value of the '{@link io.typefox.xtext.langserver.example.myDsl.dataitem_reference#getDataitem_reference_item_name <em>Dataitem reference item name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dataitem reference item name</em>' attribute.
   * @see #getDataitem_reference_item_name()
   * @generated
   */
  void setDataitem_reference_item_name(String value);

} // dataitem_reference
