/**
 * generated by Xtext 2.13.0
 */
package io.typefox.xtext.langserver.example.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>dependencies definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.dependencies_definition#getDependency_reference <em>Dependency reference</em>}</li>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.dependencies_definition#getDependency_reference2 <em>Dependency reference2</em>}</li>
 * </ul>
 *
 * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#getdependencies_definition()
 * @model
 * @generated
 */
public interface dependencies_definition extends EObject
{
  /**
   * Returns the value of the '<em><b>Dependency reference</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Dependency reference</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dependency reference</em>' attribute.
   * @see #setDependency_reference(String)
   * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#getdependencies_definition_Dependency_reference()
   * @model
   * @generated
   */
  String getDependency_reference();

  /**
   * Sets the value of the '{@link io.typefox.xtext.langserver.example.myDsl.dependencies_definition#getDependency_reference <em>Dependency reference</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dependency reference</em>' attribute.
   * @see #getDependency_reference()
   * @generated
   */
  void setDependency_reference(String value);

  /**
   * Returns the value of the '<em><b>Dependency reference2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Dependency reference2</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dependency reference2</em>' attribute.
   * @see #setDependency_reference2(String)
   * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#getdependencies_definition_Dependency_reference2()
   * @model
   * @generated
   */
  String getDependency_reference2();

  /**
   * Sets the value of the '{@link io.typefox.xtext.langserver.example.myDsl.dependencies_definition#getDependency_reference2 <em>Dependency reference2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dependency reference2</em>' attribute.
   * @see #getDependency_reference2()
   * @generated
   */
  void setDependency_reference2(String value);

} // dependencies_definition
