/**
 * generated by Xtext 2.13.0
 */
package io.typefox.xtext.langserver.example.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>entity set definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.entity_set_definition#getDynamic_component_dependency <em>Dynamic component dependency</em>}</li>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.entity_set_definition#getEntitySetName <em>Entity Set Name</em>}</li>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.entity_set_definition#getReferenceObjectName <em>Reference Object Name</em>}</li>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.entity_set_definition#getAlt <em>Alt</em>}</li>
 * </ul>
 *
 * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#getentity_set_definition()
 * @model
 * @generated
 */
public interface entity_set_definition extends MainElement
{
  /**
   * Returns the value of the '<em><b>Dynamic component dependency</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Dynamic component dependency</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dynamic component dependency</em>' containment reference.
   * @see #setDynamic_component_dependency(dynamic_component_dependency)
   * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#getentity_set_definition_Dynamic_component_dependency()
   * @model containment="true"
   * @generated
   */
  dynamic_component_dependency getDynamic_component_dependency();

  /**
   * Sets the value of the '{@link io.typefox.xtext.langserver.example.myDsl.entity_set_definition#getDynamic_component_dependency <em>Dynamic component dependency</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dynamic component dependency</em>' containment reference.
   * @see #getDynamic_component_dependency()
   * @generated
   */
  void setDynamic_component_dependency(dynamic_component_dependency value);

  /**
   * Returns the value of the '<em><b>Entity Set Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Entity Set Name</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entity Set Name</em>' containment reference.
   * @see #setEntitySetName(identifier)
   * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#getentity_set_definition_EntitySetName()
   * @model containment="true"
   * @generated
   */
  identifier getEntitySetName();

  /**
   * Sets the value of the '{@link io.typefox.xtext.langserver.example.myDsl.entity_set_definition#getEntitySetName <em>Entity Set Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Entity Set Name</em>' containment reference.
   * @see #getEntitySetName()
   * @generated
   */
  void setEntitySetName(identifier value);

  /**
   * Returns the value of the '<em><b>Reference Object Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Reference Object Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Reference Object Name</em>' attribute.
   * @see #setReferenceObjectName(String)
   * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#getentity_set_definition_ReferenceObjectName()
   * @model
   * @generated
   */
  String getReferenceObjectName();

  /**
   * Sets the value of the '{@link io.typefox.xtext.langserver.example.myDsl.entity_set_definition#getReferenceObjectName <em>Reference Object Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Reference Object Name</em>' attribute.
   * @see #getReferenceObjectName()
   * @generated
   */
  void setReferenceObjectName(String value);

  /**
   * Returns the value of the '<em><b>Alt</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Alt</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Alt</em>' containment reference.
   * @see #setAlt(EObject)
   * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#getentity_set_definition_Alt()
   * @model containment="true"
   * @generated
   */
  EObject getAlt();

  /**
   * Sets the value of the '{@link io.typefox.xtext.langserver.example.myDsl.entity_set_definition#getAlt <em>Alt</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Alt</em>' containment reference.
   * @see #getAlt()
   * @generated
   */
  void setAlt(EObject value);

} // entity_set_definition
