/**
 * generated by Xtext 2.13.0
 */
package io.typefox.xtext.langserver.example.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>enumeration type definition</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#getenumeration_type_definition()
 * @model
 * @generated
 */
public interface enumeration_type_definition extends EObject
{
} // enumeration_type_definition
