/**
 * generated by Xtext 2.13.0
 */
package io.typefox.xtext.langserver.example.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>enumeration definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.enumeration_definition#getDynamic_component_dependency <em>Dynamic component dependency</em>}</li>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.enumeration_definition#getEnumeration_type_definition <em>Enumeration type definition</em>}</li>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.enumeration_definition#getExec_definition <em>Exec definition</em>}</li>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.enumeration_definition#getEnumeration_value_definition <em>Enumeration value definition</em>}</li>
 * </ul>
 *
 * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#getenumeration_definition()
 * @model
 * @generated
 */
public interface enumeration_definition extends MainElement
{
  /**
   * Returns the value of the '<em><b>Dynamic component dependency</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Dynamic component dependency</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dynamic component dependency</em>' containment reference.
   * @see #setDynamic_component_dependency(dynamic_component_dependency)
   * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#getenumeration_definition_Dynamic_component_dependency()
   * @model containment="true"
   * @generated
   */
  dynamic_component_dependency getDynamic_component_dependency();

  /**
   * Sets the value of the '{@link io.typefox.xtext.langserver.example.myDsl.enumeration_definition#getDynamic_component_dependency <em>Dynamic component dependency</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dynamic component dependency</em>' containment reference.
   * @see #getDynamic_component_dependency()
   * @generated
   */
  void setDynamic_component_dependency(dynamic_component_dependency value);

  /**
   * Returns the value of the '<em><b>Enumeration type definition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Enumeration type definition</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Enumeration type definition</em>' containment reference.
   * @see #setEnumeration_type_definition(enumeration_type_definition)
   * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#getenumeration_definition_Enumeration_type_definition()
   * @model containment="true"
   * @generated
   */
  enumeration_type_definition getEnumeration_type_definition();

  /**
   * Sets the value of the '{@link io.typefox.xtext.langserver.example.myDsl.enumeration_definition#getEnumeration_type_definition <em>Enumeration type definition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Enumeration type definition</em>' containment reference.
   * @see #getEnumeration_type_definition()
   * @generated
   */
  void setEnumeration_type_definition(enumeration_type_definition value);

  /**
   * Returns the value of the '<em><b>Exec definition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Exec definition</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exec definition</em>' containment reference.
   * @see #setExec_definition(exec_definition)
   * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#getenumeration_definition_Exec_definition()
   * @model containment="true"
   * @generated
   */
  exec_definition getExec_definition();

  /**
   * Sets the value of the '{@link io.typefox.xtext.langserver.example.myDsl.enumeration_definition#getExec_definition <em>Exec definition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exec definition</em>' containment reference.
   * @see #getExec_definition()
   * @generated
   */
  void setExec_definition(exec_definition value);

  /**
   * Returns the value of the '<em><b>Enumeration value definition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Enumeration value definition</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Enumeration value definition</em>' containment reference.
   * @see #setEnumeration_value_definition(enumeration_value_definition)
   * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#getenumeration_definition_Enumeration_value_definition()
   * @model containment="true"
   * @generated
   */
  enumeration_value_definition getEnumeration_value_definition();

  /**
   * Sets the value of the '{@link io.typefox.xtext.langserver.example.myDsl.enumeration_definition#getEnumeration_value_definition <em>Enumeration value definition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Enumeration value definition</em>' containment reference.
   * @see #getEnumeration_value_definition()
   * @generated
   */
  void setEnumeration_value_definition(enumeration_value_definition value);

} // enumeration_definition
