/**
 * generated by Xtext 2.13.0
 */
package io.typefox.xtext.langserver.example.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>filter column definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.filter_column_definition#getFilter_column_definition_filter_column_name <em>Filter column definition filter column name</em>}</li>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.filter_column_definition#getFilter_column_operator <em>Filter column operator</em>}</li>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.filter_column_definition#getNull_image <em>Null image</em>}</li>
 * </ul>
 *
 * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#getfilter_column_definition()
 * @model
 * @generated
 */
public interface filter_column_definition extends EObject
{
  /**
   * Returns the value of the '<em><b>Filter column definition filter column name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Filter column definition filter column name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Filter column definition filter column name</em>' attribute.
   * @see #setFilter_column_definition_filter_column_name(String)
   * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#getfilter_column_definition_Filter_column_definition_filter_column_name()
   * @model
   * @generated
   */
  String getFilter_column_definition_filter_column_name();

  /**
   * Sets the value of the '{@link io.typefox.xtext.langserver.example.myDsl.filter_column_definition#getFilter_column_definition_filter_column_name <em>Filter column definition filter column name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Filter column definition filter column name</em>' attribute.
   * @see #getFilter_column_definition_filter_column_name()
   * @generated
   */
  void setFilter_column_definition_filter_column_name(String value);

  /**
   * Returns the value of the '<em><b>Filter column operator</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Filter column operator</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Filter column operator</em>' containment reference.
   * @see #setFilter_column_operator(filter_column_operator)
   * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#getfilter_column_definition_Filter_column_operator()
   * @model containment="true"
   * @generated
   */
  filter_column_operator getFilter_column_operator();

  /**
   * Sets the value of the '{@link io.typefox.xtext.langserver.example.myDsl.filter_column_definition#getFilter_column_operator <em>Filter column operator</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Filter column operator</em>' containment reference.
   * @see #getFilter_column_operator()
   * @generated
   */
  void setFilter_column_operator(filter_column_operator value);

  /**
   * Returns the value of the '<em><b>Null image</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Null image</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Null image</em>' containment reference.
   * @see #setNull_image(null_image)
   * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#getfilter_column_definition_Null_image()
   * @model containment="true"
   * @generated
   */
  null_image getNull_image();

  /**
   * Sets the value of the '{@link io.typefox.xtext.langserver.example.myDsl.filter_column_definition#getNull_image <em>Null image</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Null image</em>' containment reference.
   * @see #getNull_image()
   * @generated
   */
  void setNull_image(null_image value);

} // filter_column_definition
