/**
 * generated by Xtext 2.13.0
 */
package io.typefox.xtext.langserver.example.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>guard function</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.guard_function#getGuard_function_guard_function_name <em>Guard function guard function name</em>}</li>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.guard_function#getGuard_function_argument <em>Guard function argument</em>}</li>
 * </ul>
 *
 * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#getguard_function()
 * @model
 * @generated
 */
public interface guard_function extends EObject
{
  /**
   * Returns the value of the '<em><b>Guard function guard function name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Guard function guard function name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Guard function guard function name</em>' attribute.
   * @see #setGuard_function_guard_function_name(String)
   * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#getguard_function_Guard_function_guard_function_name()
   * @model
   * @generated
   */
  String getGuard_function_guard_function_name();

  /**
   * Sets the value of the '{@link io.typefox.xtext.langserver.example.myDsl.guard_function#getGuard_function_guard_function_name <em>Guard function guard function name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Guard function guard function name</em>' attribute.
   * @see #getGuard_function_guard_function_name()
   * @generated
   */
  void setGuard_function_guard_function_name(String value);

  /**
   * Returns the value of the '<em><b>Guard function argument</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Guard function argument</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Guard function argument</em>' attribute.
   * @see #setGuard_function_argument(String)
   * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#getguard_function_Guard_function_argument()
   * @model
   * @generated
   */
  String getGuard_function_argument();

  /**
   * Sets the value of the '{@link io.typefox.xtext.langserver.example.myDsl.guard_function#getGuard_function_argument <em>Guard function argument</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Guard function argument</em>' attribute.
   * @see #getGuard_function_argument()
   * @generated
   */
  void setGuard_function_argument(String value);

} // guard_function
