/**
 * generated by Xtext 2.13.0
 */
package io.typefox.xtext.langserver.example.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>language dependent definition</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#getlanguage_dependent_definition()
 * @model
 * @generated
 */
public interface language_dependent_definition extends EObject
{
} // language_dependent_definition
