/**
 * generated by Xtext 2.13.0
 */
package io.typefox.xtext.langserver.example.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Main Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.MainElement#getVirtual_definition <em>Virtual definition</em>}</li>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.MainElement#getQuery_definition <em>Query definition</em>}</li>
 * </ul>
 *
 * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#getMainElement()
 * @model
 * @generated
 */
public interface MainElement extends EObject
{
  /**
   * Returns the value of the '<em><b>Virtual definition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Virtual definition</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Virtual definition</em>' containment reference.
   * @see #setVirtual_definition(virtual_definition)
   * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#getMainElement_Virtual_definition()
   * @model containment="true"
   * @generated
   */
  virtual_definition getVirtual_definition();

  /**
   * Sets the value of the '{@link io.typefox.xtext.langserver.example.myDsl.MainElement#getVirtual_definition <em>Virtual definition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Virtual definition</em>' containment reference.
   * @see #getVirtual_definition()
   * @generated
   */
  void setVirtual_definition(virtual_definition value);

  /**
   * Returns the value of the '<em><b>Query definition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Query definition</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Query definition</em>' containment reference.
   * @see #setQuery_definition(query_definition)
   * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#getMainElement_Query_definition()
   * @model containment="true"
   * @generated
   */
  query_definition getQuery_definition();

  /**
   * Sets the value of the '{@link io.typefox.xtext.langserver.example.myDsl.MainElement#getQuery_definition <em>Query definition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Query definition</em>' containment reference.
   * @see #getQuery_definition()
   * @generated
   */
  void setQuery_definition(query_definition value);

} // MainElement
