/**
 * generated by Xtext 2.13.0
 */
package io.typefox.xtext.langserver.example.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>mapping arguments</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.mapping_arguments#getMapping_argument <em>Mapping argument</em>}</li>
 * </ul>
 *
 * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#getmapping_arguments()
 * @model
 * @generated
 */
public interface mapping_arguments extends EObject
{
  /**
   * Returns the value of the '<em><b>Mapping argument</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Mapping argument</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mapping argument</em>' attribute.
   * @see #setMapping_argument(String)
   * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#getmapping_arguments_Mapping_argument()
   * @model
   * @generated
   */
  String getMapping_argument();

  /**
   * Sets the value of the '{@link io.typefox.xtext.langserver.example.myDsl.mapping_arguments#getMapping_argument <em>Mapping argument</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Mapping argument</em>' attribute.
   * @see #getMapping_argument()
   * @generated
   */
  void setMapping_argument(String value);

} // mapping_arguments
