/**
 * generated by Xtext 2.13.0
 */
package io.typefox.xtext.langserver.example.myDsl;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage
 * @generated
 */
public interface MyDslFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDslFactory eINSTANCE = io.typefox.xtext.langserver.example.myDsl.impl.MyDslFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Domainmodel</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Domainmodel</em>'.
   * @generated
   */
  Domainmodel createDomainmodel();

  /**
   * Returns a new object of class '<em>Main Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Main Element</em>'.
   * @generated
   */
  MainElement createMainElement();

  /**
   * Returns a new object of class '<em>projection name</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>projection name</em>'.
   * @generated
   */
  projection_name createprojection_name();

  /**
   * Returns a new object of class '<em>projection component</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>projection component</em>'.
   * @generated
   */
  projection_component createprojection_component();

  /**
   * Returns a new object of class '<em>layer specification</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>layer specification</em>'.
   * @generated
   */
  layer_specification createlayer_specification();

  /**
   * Returns a new object of class '<em>description</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>description</em>'.
   * @generated
   */
  description createdescription();

  /**
   * Returns a new object of class '<em>capability</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>capability</em>'.
   * @generated
   */
  capability createcapability();

  /**
   * Returns a new object of class '<em>category</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>category</em>'.
   * @generated
   */
  category createcategory();

  /**
   * Returns a new object of class '<em>service group</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>service group</em>'.
   * @generated
   */
  service_group createservice_group();

  /**
   * Returns a new object of class '<em>include fragment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>include fragment</em>'.
   * @generated
   */
  include_fragment createinclude_fragment();

  /**
   * Returns a new object of class '<em>override</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>override</em>'.
   * @generated
   */
  override createoverride();

  /**
   * Returns a new object of class '<em>overtake</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>overtake</em>'.
   * @generated
   */
  overtake createovertake();

  /**
   * Returns a new object of class '<em>entity set definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>entity set definition</em>'.
   * @generated
   */
  entity_set_definition createentity_set_definition();

  /**
   * Returns a new object of class '<em>where definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>where definition</em>'.
   * @generated
   */
  where_definition createwhere_definition();

  /**
   * Returns a new object of class '<em>filtering context list definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>filtering context list definition</em>'.
   * @generated
   */
  filtering_context_list_definition createfiltering_context_list_definition();

  /**
   * Returns a new object of class '<em>offline filter definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>offline filter definition</em>'.
   * @generated
   */
  offline_filter_definition createoffline_filter_definition();

  /**
   * Returns a new object of class '<em>singleton set definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>singleton set definition</em>'.
   * @generated
   */
  singleton_set_definition createsingleton_set_definition();

  /**
   * Returns a new object of class '<em>computeditem definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>computeditem definition</em>'.
   * @generated
   */
  computeditem_definition createcomputeditem_definition();

  /**
   * Returns a new object of class '<em>compute definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>compute definition</em>'.
   * @generated
   */
  compute_definition createcompute_definition();

  /**
   * Returns a new object of class '<em>compute expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>compute expression</em>'.
   * @generated
   */
  compute_expression createcompute_expression();

  /**
   * Returns a new object of class '<em>compute expression atom</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>compute expression atom</em>'.
   * @generated
   */
  compute_expression_atom createcompute_expression_atom();

  /**
   * Returns a new object of class '<em>compute expression atom value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>compute expression atom value</em>'.
   * @generated
   */
  compute_expression_atom_value createcompute_expression_atom_value();

  /**
   * Returns a new object of class '<em>datasource definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>datasource definition</em>'.
   * @generated
   */
  datasource_definition createdatasource_definition();

  /**
   * Returns a new object of class '<em>key fetch on create flag</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>key fetch on create flag</em>'.
   * @generated
   */
  key_fetch_on_create_flag createkey_fetch_on_create_flag();

  /**
   * Returns a new object of class '<em>luname definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>luname definition</em>'.
   * @generated
   */
  luname_definition createluname_definition();

  /**
   * Returns a new object of class '<em>keyref definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>keyref definition</em>'.
   * @generated
   */
  keyref_definition createkeyref_definition();

  /**
   * Returns a new object of class '<em>validate action reference</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>validate action reference</em>'.
   * @generated
   */
  validate_action_reference createvalidate_action_reference();

  /**
   * Returns a new object of class '<em>statemachine definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>statemachine definition</em>'.
   * @generated
   */
  statemachine_definition createstatemachine_definition();

  /**
   * Returns a new object of class '<em>state event definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>state event definition</em>'.
   * @generated
   */
  state_event_definition createstate_event_definition();

  /**
   * Returns a new object of class '<em>use attributes definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>use attributes definition</em>'.
   * @generated
   */
  use_attributes_definition createuse_attributes_definition();

  /**
   * Returns a new object of class '<em>exclude attributes definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>exclude attributes definition</em>'.
   * @generated
   */
  exclude_attributes_definition createexclude_attributes_definition();

  /**
   * Returns a new object of class '<em>tag definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>tag definition</em>'.
   * @generated
   */
  tag_definition createtag_definition();

  /**
   * Returns a new object of class '<em>tag union definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>tag union definition</em>'.
   * @generated
   */
  tag_union_definition createtag_union_definition();

  /**
   * Returns a new object of class '<em>tag minus definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>tag minus definition</em>'.
   * @generated
   */
  tag_minus_definition createtag_minus_definition();

  /**
   * Returns a new object of class '<em>tag intersect definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>tag intersect definition</em>'.
   * @generated
   */
  tag_intersect_definition createtag_intersect_definition();

  /**
   * Returns a new object of class '<em>sync policy definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>sync policy definition</em>'.
   * @generated
   */
  sync_policy_definition createsync_policy_definition();

  /**
   * Returns a new object of class '<em>batch sync policy definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>batch sync policy definition</em>'.
   * @generated
   */
  batch_sync_policy_definition createbatch_sync_policy_definition();

  /**
   * Returns a new object of class '<em>sync schedule definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>sync schedule definition</em>'.
   * @generated
   */
  sync_schedule_definition createsync_schedule_definition();

  /**
   * Returns a new object of class '<em>batch sync hourly policy</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>batch sync hourly policy</em>'.
   * @generated
   */
  batch_sync_hourly_policy createbatch_sync_hourly_policy();

  /**
   * Returns a new object of class '<em>batch sync daily policy</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>batch sync daily policy</em>'.
   * @generated
   */
  batch_sync_daily_policy createbatch_sync_daily_policy();

  /**
   * Returns a new object of class '<em>batch sync weekly policy</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>batch sync weekly policy</em>'.
   * @generated
   */
  batch_sync_weekly_policy createbatch_sync_weekly_policy();

  /**
   * Returns a new object of class '<em>batch sync weekday</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>batch sync weekday</em>'.
   * @generated
   */
  batch_sync_weekday createbatch_sync_weekday();

  /**
   * Returns a new object of class '<em>batch sync monthly policy</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>batch sync monthly policy</em>'.
   * @generated
   */
  batch_sync_monthly_policy createbatch_sync_monthly_policy();

  /**
   * Returns a new object of class '<em>sync group definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>sync group definition</em>'.
   * @generated
   */
  sync_group_definition createsync_group_definition();

  /**
   * Returns a new object of class '<em>filter on entity setting</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>filter on entity setting</em>'.
   * @generated
   */
  filter_on_entity_setting createfilter_on_entity_setting();

  /**
   * Returns a new object of class '<em>incoming sync policy definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>incoming sync policy definition</em>'.
   * @generated
   */
  incoming_sync_policy_definition createincoming_sync_policy_definition();

  /**
   * Returns a new object of class '<em>client cache sync policy definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>client cache sync policy definition</em>'.
   * @generated
   */
  client_cache_sync_policy_definition createclient_cache_sync_policy_definition();

  /**
   * Returns a new object of class '<em>cache invalidation definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>cache invalidation definition</em>'.
   * @generated
   */
  cache_invalidation_definition createcache_invalidation_definition();

  /**
   * Returns a new object of class '<em>cache invalidation after</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>cache invalidation after</em>'.
   * @generated
   */
  cache_invalidation_after createcache_invalidation_after();

  /**
   * Returns a new object of class '<em>online only sync policy definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>online only sync policy definition</em>'.
   * @generated
   */
  online_only_sync_policy_definition createonline_only_sync_policy_definition();

  /**
   * Returns a new object of class '<em>push sync policy definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>push sync policy definition</em>'.
   * @generated
   */
  push_sync_policy_definition createpush_sync_policy_definition();

  /**
   * Returns a new object of class '<em>guard condition definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>guard condition definition</em>'.
   * @generated
   */
  guard_condition_definition createguard_condition_definition();

  /**
   * Returns a new object of class '<em>ownership query definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>ownership query definition</em>'.
   * @generated
   */
  ownership_query_definition createownership_query_definition();

  /**
   * Returns a new object of class '<em>exclude details setting</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>exclude details setting</em>'.
   * @generated
   */
  exclude_details_setting createexclude_details_setting();

  /**
   * Returns a new object of class '<em>grouped push sync policy definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>grouped push sync policy definition</em>'.
   * @generated
   */
  grouped_push_sync_policy_definition creategrouped_push_sync_policy_definition();

  /**
   * Returns a new object of class '<em>user filter reference</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>user filter reference</em>'.
   * @generated
   */
  user_filter_reference createuser_filter_reference();

  /**
   * Returns a new object of class '<em>language dependent definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>language dependent definition</em>'.
   * @generated
   */
  language_dependent_definition createlanguage_dependent_definition();

  /**
   * Returns a new object of class '<em>language dependent definition language dependent type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>language dependent definition language dependent type</em>'.
   * @generated
   */
  language_dependent_definition_language_dependent_type createlanguage_dependent_definition_language_dependent_type();

  /**
   * Returns a new object of class '<em>change detection definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>change detection definition</em>'.
   * @generated
   */
  change_detection_definition createchange_detection_definition();

  /**
   * Returns a new object of class '<em>trigger</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>trigger</em>'.
   * @generated
   */
  trigger createtrigger();

  /**
   * Returns a new object of class '<em>trigger attributes</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>trigger attributes</em>'.
   * @generated
   */
  trigger_attributes createtrigger_attributes();

  /**
   * Returns a new object of class '<em>trigger attribute</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>trigger attribute</em>'.
   * @generated
   */
  trigger_attribute createtrigger_attribute();

  /**
   * Returns a new object of class '<em>combine attribute</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>combine attribute</em>'.
   * @generated
   */
  combine_attribute createcombine_attribute();

  /**
   * Returns a new object of class '<em>trigger attribute table columns</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>trigger attribute table columns</em>'.
   * @generated
   */
  trigger_attribute_table_columns createtrigger_attribute_table_columns();

  /**
   * Returns a new object of class '<em>mapping arguments</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>mapping arguments</em>'.
   * @generated
   */
  mapping_arguments createmapping_arguments();

  /**
   * Returns a new object of class '<em>objkey column</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>objkey column</em>'.
   * @generated
   */
  objkey_column createobjkey_column();

  /**
   * Returns a new object of class '<em>target table</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>target table</em>'.
   * @generated
   */
  target_table createtarget_table();

  /**
   * Returns a new object of class '<em>objkey mapping</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>objkey mapping</em>'.
   * @generated
   */
  objkey_mapping createobjkey_mapping();

  /**
   * Returns a new object of class '<em>guard function</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>guard function</em>'.
   * @generated
   */
  guard_function createguard_function();

  /**
   * Returns a new object of class '<em>exclude from config flag setting</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>exclude from config flag setting</em>'.
   * @generated
   */
  exclude_from_config_flag_setting createexclude_from_config_flag_setting();

  /**
   * Returns a new object of class '<em>summary definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>summary definition</em>'.
   * @generated
   */
  summary_definition createsummary_definition();

  /**
   * Returns a new object of class '<em>query definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>query definition</em>'.
   * @generated
   */
  query_definition createquery_definition();

  /**
   * Returns a new object of class '<em>lu definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>lu definition</em>'.
   * @generated
   */
  lu_definition createlu_definition();

  /**
   * Returns a new object of class '<em>enumeration definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>enumeration definition</em>'.
   * @generated
   */
  enumeration_definition createenumeration_definition();

  /**
   * Returns a new object of class '<em>enumeration type definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>enumeration type definition</em>'.
   * @generated
   */
  enumeration_type_definition createenumeration_type_definition();

  /**
   * Returns a new object of class '<em>enumeration type definition enumeration type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>enumeration type definition enumeration type</em>'.
   * @generated
   */
  enumeration_type_definition_enumeration_type createenumeration_type_definition_enumeration_type();

  /**
   * Returns a new object of class '<em>enumeration value definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>enumeration value definition</em>'.
   * @generated
   */
  enumeration_value_definition createenumeration_value_definition();

  /**
   * Returns a new object of class '<em>exec definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>exec definition</em>'.
   * @generated
   */
  exec_definition createexec_definition();

  /**
   * Returns a new object of class '<em>label definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>label definition</em>'.
   * @generated
   */
  label_definition createlabel_definition();

  /**
   * Returns a new object of class '<em>user filter definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>user filter definition</em>'.
   * @generated
   */
  user_filter_definition createuser_filter_definition();

  /**
   * Returns a new object of class '<em>view filter definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>view filter definition</em>'.
   * @generated
   */
  view_filter_definition createview_filter_definition();

  /**
   * Returns a new object of class '<em>user column definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>user column definition</em>'.
   * @generated
   */
  user_column_definition createuser_column_definition();

  /**
   * Returns a new object of class '<em>filter columns definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>filter columns definition</em>'.
   * @generated
   */
  filter_columns_definition createfilter_columns_definition();

  /**
   * Returns a new object of class '<em>filter column definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>filter column definition</em>'.
   * @generated
   */
  filter_column_definition createfilter_column_definition();

  /**
   * Returns a new object of class '<em>filter column operator</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>filter column operator</em>'.
   * @generated
   */
  filter_column_operator createfilter_column_operator();

  /**
   * Returns a new object of class '<em>filter column operator filter column operator name</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>filter column operator filter column operator name</em>'.
   * @generated
   */
  filter_column_operator_filter_column_operator_name createfilter_column_operator_filter_column_operator_name();

  /**
   * Returns a new object of class '<em>null image</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>null image</em>'.
   * @generated
   */
  null_image createnull_image();

  /**
   * Returns a new object of class '<em>null image null match</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>null image null match</em>'.
   * @generated
   */
  null_image_null_match createnull_image_null_match();

  /**
   * Returns a new object of class '<em>trigger on definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>trigger on definition</em>'.
   * @generated
   */
  trigger_on_definition createtrigger_on_definition();

  /**
   * Returns a new object of class '<em>action definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>action definition</em>'.
   * @generated
   */
  action_definition createaction_definition();

  /**
   * Returns a new object of class '<em>type definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>type definition</em>'.
   * @generated
   */
  type_definition createtype_definition();

  /**
   * Returns a new object of class '<em>implementation definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>implementation definition</em>'.
   * @generated
   */
  implementation_definition createimplementation_definition();

  /**
   * Returns a new object of class '<em>dependency definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>dependency definition</em>'.
   * @generated
   */
  dependency_definition createdependency_definition();

  /**
   * Returns a new object of class '<em>server package reference</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>server package reference</em>'.
   * @generated
   */
  server_package_reference createserver_package_reference();

  /**
   * Returns a new object of class '<em>dependencies definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>dependencies definition</em>'.
   * @generated
   */
  dependencies_definition createdependencies_definition();

  /**
   * Returns a new object of class '<em>mandatory flag setting</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>mandatory flag setting</em>'.
   * @generated
   */
  mandatory_flag_setting createmandatory_flag_setting();

  /**
   * Returns a new object of class '<em>projection flag condition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>projection flag condition</em>'.
   * @generated
   */
  projection_flag_condition createprojection_flag_condition();

  /**
   * Returns a new object of class '<em>projection flag condition atom</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>projection flag condition atom</em>'.
   * @generated
   */
  projection_flag_condition_atom createprojection_flag_condition_atom();

  /**
   * Returns a new object of class '<em>projection flag condition atom value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>projection flag condition atom value</em>'.
   * @generated
   */
  projection_flag_condition_atom_value createprojection_flag_condition_atom_value();

  /**
   * Returns a new object of class '<em>parameter definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>parameter definition</em>'.
   * @generated
   */
  parameter_definition createparameter_definition();

  /**
   * Returns a new object of class '<em>available flag setting</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>available flag setting</em>'.
   * @generated
   */
  available_flag_setting createavailable_flag_setting();

  /**
   * Returns a new object of class '<em>transaction group definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>transaction group definition</em>'.
   * @generated
   */
  transaction_group_definition createtransaction_group_definition();

  /**
   * Returns a new object of class '<em>offline sync policy definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>offline sync policy definition</em>'.
   * @generated
   */
  offline_sync_policy_definition createoffline_sync_policy_definition();

  /**
   * Returns a new object of class '<em>support warnings flag setting</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>support warnings flag setting</em>'.
   * @generated
   */
  support_warnings_flag_setting createsupport_warnings_flag_setting();

  /**
   * Returns a new object of class '<em>function definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>function definition</em>'.
   * @generated
   */
  function_definition createfunction_definition();

  /**
   * Returns a new object of class '<em>based on entity set definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>based on entity set definition</em>'.
   * @generated
   */
  based_on_entity_set_definition createbased_on_entity_set_definition();

  /**
   * Returns a new object of class '<em>support file info flag</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>support file info flag</em>'.
   * @generated
   */
  support_file_info_flag createsupport_file_info_flag();

  /**
   * Returns a new object of class '<em>from definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>from definition</em>'.
   * @generated
   */
  from_definition createfrom_definition();

  /**
   * Returns a new object of class '<em>alter attribute definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>alter attribute definition</em>'.
   * @generated
   */
  alter_attribute_definition createalter_attribute_definition();

  /**
   * Returns a new object of class '<em>fetch definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>fetch definition</em>'.
   * @generated
   */
  fetch_definition createfetch_definition();

  /**
   * Returns a new object of class '<em>complextype definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>complextype definition</em>'.
   * @generated
   */
  complextype_definition createcomplextype_definition();

  /**
   * Returns a new object of class '<em>virtual definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>virtual definition</em>'.
   * @generated
   */
  virtual_definition createvirtual_definition();

  /**
   * Returns a new object of class '<em>warnings enabled flag</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>warnings enabled flag</em>'.
   * @generated
   */
  warnings_enabled_flag createwarnings_enabled_flag();

  /**
   * Returns a new object of class '<em>keys definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>keys definition</em>'.
   * @generated
   */
  keys_definition createkeys_definition();

  /**
   * Returns a new object of class '<em>crud definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>crud definition</em>'.
   * @generated
   */
  crud_definition createcrud_definition();

  /**
   * Returns a new object of class '<em>crud reference</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>crud reference</em>'.
   * @generated
   */
  crud_reference createcrud_reference();

  /**
   * Returns a new object of class '<em>dataitem definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>dataitem definition</em>'.
   * @generated
   */
  dataitem_definition createdataitem_definition();

  /**
   * Returns a new object of class '<em>enum lookup list flag setting</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>enum lookup list flag setting</em>'.
   * @generated
   */
  enum_lookup_list_flag_setting createenum_lookup_list_flag_setting();

  /**
   * Returns a new object of class '<em>default data definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>default data definition</em>'.
   * @generated
   */
  default_data_definition createdefault_data_definition();

  /**
   * Returns a new object of class '<em>regexp definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>regexp definition</em>'.
   * @generated
   */
  regexp_definition createregexp_definition();

  /**
   * Returns a new object of class '<em>maxlength definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>maxlength definition</em>'.
   * @generated
   */
  maxlength_definition createmaxlength_definition();

  /**
   * Returns a new object of class '<em>format definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>format definition</em>'.
   * @generated
   */
  format_definition createformat_definition();

  /**
   * Returns a new object of class '<em>inline property setting</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>inline property setting</em>'.
   * @generated
   */
  inline_property_setting createinline_property_setting();

  /**
   * Returns a new object of class '<em>lov flag setting</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>lov flag setting</em>'.
   * @generated
   */
  lov_flag_setting createlov_flag_setting();

  /**
   * Returns a new object of class '<em>updatable flag setting</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>updatable flag setting</em>'.
   * @generated
   */
  updatable_flag_setting createupdatable_flag_setting();

  /**
   * Returns a new object of class '<em>server updatable flag setting</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>server updatable flag setting</em>'.
   * @generated
   */
  server_updatable_flag_setting createserver_updatable_flag_setting();

  /**
   * Returns a new object of class '<em>server insertable flag setting</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>server insertable flag setting</em>'.
   * @generated
   */
  server_insertable_flag_setting createserver_insertable_flag_setting();

  /**
   * Returns a new object of class '<em>validation definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>validation definition</em>'.
   * @generated
   */
  validation_definition createvalidation_definition();

  /**
   * Returns a new object of class '<em>implementation type definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>implementation type definition</em>'.
   * @generated
   */
  implementation_type_definition createimplementation_type_definition();

  /**
   * Returns a new object of class '<em>stream file info definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>stream file info definition</em>'.
   * @generated
   */
  stream_file_info_definition createstream_file_info_definition();

  /**
   * Returns a new object of class '<em>stream file name attribute</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>stream file name attribute</em>'.
   * @generated
   */
  stream_file_name_attribute createstream_file_name_attribute();

  /**
   * Returns a new object of class '<em>stream mime type attribute</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>stream mime type attribute</em>'.
   * @generated
   */
  stream_mime_type_attribute createstream_mime_type_attribute();

  /**
   * Returns a new object of class '<em>stream attachment attribute</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>stream attachment attribute</em>'.
   * @generated
   */
  stream_attachment_attribute createstream_attachment_attribute();

  /**
   * Returns a new object of class '<em>dataitem reference</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>dataitem reference</em>'.
   * @generated
   */
  dataitem_reference createdataitem_reference();

  /**
   * Returns a new object of class '<em>aggregate definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>aggregate definition</em>'.
   * @generated
   */
  aggregate_definition createaggregate_definition();

  /**
   * Returns a new object of class '<em>key reference</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>key reference</em>'.
   * @generated
   */
  key_reference createkey_reference();

  /**
   * Returns a new object of class '<em>to reference definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>to reference definition</em>'.
   * @generated
   */
  to_reference_definition createto_reference_definition();

  /**
   * Returns a new object of class '<em>to function definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>to function definition</em>'.
   * @generated
   */
  to_function_definition createto_function_definition();

  /**
   * Returns a new object of class '<em>prefetch definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>prefetch definition</em>'.
   * @generated
   */
  prefetch_definition createprefetch_definition();

  /**
   * Returns a new object of class '<em>copy definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>copy definition</em>'.
   * @generated
   */
  copy_definition createcopy_definition();

  /**
   * Returns a new object of class '<em>where filter definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>where filter definition</em>'.
   * @generated
   */
  where_filter_definition createwhere_filter_definition();

  /**
   * Returns a new object of class '<em>aggregate list flag setting</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>aggregate list flag setting</em>'.
   * @generated
   */
  aggregate_list_flag_setting createaggregate_list_flag_setting();

  /**
   * Returns a new object of class '<em>aggregate check flag setting</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>aggregate check flag setting</em>'.
   * @generated
   */
  aggregate_check_flag_setting createaggregate_check_flag_setting();

  /**
   * Returns a new object of class '<em>aggregate wildcard definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>aggregate wildcard definition</em>'.
   * @generated
   */
  aggregate_wildcard_definition createaggregate_wildcard_definition();

  /**
   * Returns a new object of class '<em>array definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>array definition</em>'.
   * @generated
   */
  array_definition createarray_definition();

  /**
   * Returns a new object of class '<em>filtering context definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>filtering context definition</em>'.
   * @generated
   */
  filtering_context_definition createfiltering_context_definition();

  /**
   * Returns a new object of class '<em>filtering context property</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>filtering context property</em>'.
   * @generated
   */
  filtering_context_property createfiltering_context_property();

  /**
   * Returns a new object of class '<em>abstract def</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>abstract def</em>'.
   * @generated
   */
  abstract_def createabstract_def();

  /**
   * Returns a new object of class '<em>dynamic component dependency</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>dynamic component dependency</em>'.
   * @generated
   */
  dynamic_component_dependency createdynamic_component_dependency();

  /**
   * Returns a new object of class '<em>identifier</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>identifier</em>'.
   * @generated
   */
  identifier createidentifier();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  MyDslPackage getMyDslPackage();

} //MyDslFactory
