/**
 * generated by Xtext 2.13.0
 */
package io.typefox.xtext.langserver.example.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>prefetch definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.prefetch_definition#getDataitem_reference <em>Dataitem reference</em>}</li>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.prefetch_definition#getPrefetch_definition_prefetch_name <em>Prefetch definition prefetch name</em>}</li>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.prefetch_definition#getLabel_definition <em>Label definition</em>}</li>
 * </ul>
 *
 * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#getprefetch_definition()
 * @model
 * @generated
 */
public interface prefetch_definition extends EObject
{
  /**
   * Returns the value of the '<em><b>Dataitem reference</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Dataitem reference</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dataitem reference</em>' containment reference.
   * @see #setDataitem_reference(dataitem_reference)
   * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#getprefetch_definition_Dataitem_reference()
   * @model containment="true"
   * @generated
   */
  dataitem_reference getDataitem_reference();

  /**
   * Sets the value of the '{@link io.typefox.xtext.langserver.example.myDsl.prefetch_definition#getDataitem_reference <em>Dataitem reference</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dataitem reference</em>' containment reference.
   * @see #getDataitem_reference()
   * @generated
   */
  void setDataitem_reference(dataitem_reference value);

  /**
   * Returns the value of the '<em><b>Prefetch definition prefetch name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Prefetch definition prefetch name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Prefetch definition prefetch name</em>' attribute.
   * @see #setPrefetch_definition_prefetch_name(String)
   * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#getprefetch_definition_Prefetch_definition_prefetch_name()
   * @model
   * @generated
   */
  String getPrefetch_definition_prefetch_name();

  /**
   * Sets the value of the '{@link io.typefox.xtext.langserver.example.myDsl.prefetch_definition#getPrefetch_definition_prefetch_name <em>Prefetch definition prefetch name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Prefetch definition prefetch name</em>' attribute.
   * @see #getPrefetch_definition_prefetch_name()
   * @generated
   */
  void setPrefetch_definition_prefetch_name(String value);

  /**
   * Returns the value of the '<em><b>Label definition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Label definition</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Label definition</em>' containment reference.
   * @see #setLabel_definition(label_definition)
   * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#getprefetch_definition_Label_definition()
   * @model containment="true"
   * @generated
   */
  label_definition getLabel_definition();

  /**
   * Sets the value of the '{@link io.typefox.xtext.langserver.example.myDsl.prefetch_definition#getLabel_definition <em>Label definition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Label definition</em>' containment reference.
   * @see #getLabel_definition()
   * @generated
   */
  void setLabel_definition(label_definition value);

} // prefetch_definition
