/**
 * generated by Xtext 2.13.0
 */
package io.typefox.xtext.langserver.example.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>projection flag condition atom</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.projection_flag_condition_atom#getAlt <em>Alt</em>}</li>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.projection_flag_condition_atom#getProjection_flag_condition_atom_dataitem_ref <em>Projection flag condition atom dataitem ref</em>}</li>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.projection_flag_condition_atom#getProjection_flag_condition_atom_value <em>Projection flag condition atom value</em>}</li>
 * </ul>
 *
 * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#getprojection_flag_condition_atom()
 * @model
 * @generated
 */
public interface projection_flag_condition_atom extends EObject
{
  /**
   * Returns the value of the '<em><b>Alt</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Alt</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Alt</em>' attribute.
   * @see #setAlt(String)
   * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#getprojection_flag_condition_atom_Alt()
   * @model
   * @generated
   */
  String getAlt();

  /**
   * Sets the value of the '{@link io.typefox.xtext.langserver.example.myDsl.projection_flag_condition_atom#getAlt <em>Alt</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Alt</em>' attribute.
   * @see #getAlt()
   * @generated
   */
  void setAlt(String value);

  /**
   * Returns the value of the '<em><b>Projection flag condition atom dataitem ref</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Projection flag condition atom dataitem ref</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Projection flag condition atom dataitem ref</em>' attribute.
   * @see #setProjection_flag_condition_atom_dataitem_ref(String)
   * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#getprojection_flag_condition_atom_Projection_flag_condition_atom_dataitem_ref()
   * @model
   * @generated
   */
  String getProjection_flag_condition_atom_dataitem_ref();

  /**
   * Sets the value of the '{@link io.typefox.xtext.langserver.example.myDsl.projection_flag_condition_atom#getProjection_flag_condition_atom_dataitem_ref <em>Projection flag condition atom dataitem ref</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Projection flag condition atom dataitem ref</em>' attribute.
   * @see #getProjection_flag_condition_atom_dataitem_ref()
   * @generated
   */
  void setProjection_flag_condition_atom_dataitem_ref(String value);

  /**
   * Returns the value of the '<em><b>Projection flag condition atom value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Projection flag condition atom value</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Projection flag condition atom value</em>' containment reference.
   * @see #setProjection_flag_condition_atom_value(projection_flag_condition_atom_value)
   * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#getprojection_flag_condition_atom_Projection_flag_condition_atom_value()
   * @model containment="true"
   * @generated
   */
  projection_flag_condition_atom_value getProjection_flag_condition_atom_value();

  /**
   * Sets the value of the '{@link io.typefox.xtext.langserver.example.myDsl.projection_flag_condition_atom#getProjection_flag_condition_atom_value <em>Projection flag condition atom value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Projection flag condition atom value</em>' containment reference.
   * @see #getProjection_flag_condition_atom_value()
   * @generated
   */
  void setProjection_flag_condition_atom_value(projection_flag_condition_atom_value value);

} // projection_flag_condition_atom
