/**
 * generated by Xtext 2.13.0
 */
package io.typefox.xtext.langserver.example.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>projection flag condition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.projection_flag_condition#getProjection_flag_condition_atom <em>Projection flag condition atom</em>}</li>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.projection_flag_condition#getProjection_flag_condition <em>Projection flag condition</em>}</li>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.projection_flag_condition#getAlt <em>Alt</em>}</li>
 * </ul>
 *
 * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#getprojection_flag_condition()
 * @model
 * @generated
 */
public interface projection_flag_condition extends EObject
{
  /**
   * Returns the value of the '<em><b>Projection flag condition atom</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Projection flag condition atom</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Projection flag condition atom</em>' containment reference.
   * @see #setProjection_flag_condition_atom(projection_flag_condition_atom)
   * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#getprojection_flag_condition_Projection_flag_condition_atom()
   * @model containment="true"
   * @generated
   */
  projection_flag_condition_atom getProjection_flag_condition_atom();

  /**
   * Sets the value of the '{@link io.typefox.xtext.langserver.example.myDsl.projection_flag_condition#getProjection_flag_condition_atom <em>Projection flag condition atom</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Projection flag condition atom</em>' containment reference.
   * @see #getProjection_flag_condition_atom()
   * @generated
   */
  void setProjection_flag_condition_atom(projection_flag_condition_atom value);

  /**
   * Returns the value of the '<em><b>Projection flag condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Projection flag condition</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Projection flag condition</em>' containment reference.
   * @see #setProjection_flag_condition(projection_flag_condition)
   * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#getprojection_flag_condition_Projection_flag_condition()
   * @model containment="true"
   * @generated
   */
  projection_flag_condition getProjection_flag_condition();

  /**
   * Sets the value of the '{@link io.typefox.xtext.langserver.example.myDsl.projection_flag_condition#getProjection_flag_condition <em>Projection flag condition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Projection flag condition</em>' containment reference.
   * @see #getProjection_flag_condition()
   * @generated
   */
  void setProjection_flag_condition(projection_flag_condition value);

  /**
   * Returns the value of the '<em><b>Alt</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Alt</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Alt</em>' attribute.
   * @see #setAlt(String)
   * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#getprojection_flag_condition_Alt()
   * @model
   * @generated
   */
  String getAlt();

  /**
   * Sets the value of the '{@link io.typefox.xtext.langserver.example.myDsl.projection_flag_condition#getAlt <em>Alt</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Alt</em>' attribute.
   * @see #getAlt()
   * @generated
   */
  void setAlt(String value);

} // projection_flag_condition
