/**
 * generated by Xtext 2.13.0
 */
package io.typefox.xtext.langserver.example.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>projection flag condition atom value</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.projection_flag_condition_atom_value#getAlt <em>Alt</em>}</li>
 * </ul>
 *
 * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#getprojection_flag_condition_atom_value()
 * @model
 * @generated
 */
public interface projection_flag_condition_atom_value extends EObject
{
  /**
   * Returns the value of the '<em><b>Alt</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Alt</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Alt</em>' attribute.
   * @see #setAlt(String)
   * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#getprojection_flag_condition_atom_value_Alt()
   * @model
   * @generated
   */
  String getAlt();

  /**
   * Sets the value of the '{@link io.typefox.xtext.langserver.example.myDsl.projection_flag_condition_atom_value#getAlt <em>Alt</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Alt</em>' attribute.
   * @see #getAlt()
   * @generated
   */
  void setAlt(String value);

} // projection_flag_condition_atom_value
