/**
 * generated by Xtext 2.13.0
 */
package io.typefox.xtext.langserver.example.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>state event definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.state_event_definition#getState_event_definition_event_name <em>State event definition event name</em>}</li>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.state_event_definition#getAlt <em>Alt</em>}</li>
 * </ul>
 *
 * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#getstate_event_definition()
 * @model
 * @generated
 */
public interface state_event_definition extends EObject
{
  /**
   * Returns the value of the '<em><b>State event definition event name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>State event definition event name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>State event definition event name</em>' attribute.
   * @see #setState_event_definition_event_name(String)
   * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#getstate_event_definition_State_event_definition_event_name()
   * @model
   * @generated
   */
  String getState_event_definition_event_name();

  /**
   * Sets the value of the '{@link io.typefox.xtext.langserver.example.myDsl.state_event_definition#getState_event_definition_event_name <em>State event definition event name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>State event definition event name</em>' attribute.
   * @see #getState_event_definition_event_name()
   * @generated
   */
  void setState_event_definition_event_name(String value);

  /**
   * Returns the value of the '<em><b>Alt</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Alt</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Alt</em>' containment reference.
   * @see #setAlt(EObject)
   * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#getstate_event_definition_Alt()
   * @model containment="true"
   * @generated
   */
  EObject getAlt();

  /**
   * Sets the value of the '{@link io.typefox.xtext.langserver.example.myDsl.state_event_definition#getAlt <em>Alt</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Alt</em>' containment reference.
   * @see #getAlt()
   * @generated
   */
  void setAlt(EObject value);

} // state_event_definition
