/**
 * generated by Xtext 2.13.0
 */
package io.typefox.xtext.langserver.example.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>statemachine definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.statemachine_definition#getState_event_definition <em>State event definition</em>}</li>
 * </ul>
 *
 * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#getstatemachine_definition()
 * @model
 * @generated
 */
public interface statemachine_definition extends EObject
{
  /**
   * Returns the value of the '<em><b>State event definition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>State event definition</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>State event definition</em>' containment reference.
   * @see #setState_event_definition(state_event_definition)
   * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#getstatemachine_definition_State_event_definition()
   * @model containment="true"
   * @generated
   */
  state_event_definition getState_event_definition();

  /**
   * Sets the value of the '{@link io.typefox.xtext.langserver.example.myDsl.statemachine_definition#getState_event_definition <em>State event definition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>State event definition</em>' containment reference.
   * @see #getState_event_definition()
   * @generated
   */
  void setState_event_definition(state_event_definition value);

} // statemachine_definition
