/**
 * generated by Xtext 2.13.0
 */
package io.typefox.xtext.langserver.example.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>stream mime type attribute</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.stream_mime_type_attribute#getDataitem_reference <em>Dataitem reference</em>}</li>
 * </ul>
 *
 * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#getstream_mime_type_attribute()
 * @model
 * @generated
 */
public interface stream_mime_type_attribute extends EObject
{
  /**
   * Returns the value of the '<em><b>Dataitem reference</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Dataitem reference</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dataitem reference</em>' containment reference.
   * @see #setDataitem_reference(dataitem_reference)
   * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#getstream_mime_type_attribute_Dataitem_reference()
   * @model containment="true"
   * @generated
   */
  dataitem_reference getDataitem_reference();

  /**
   * Sets the value of the '{@link io.typefox.xtext.langserver.example.myDsl.stream_mime_type_attribute#getDataitem_reference <em>Dataitem reference</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dataitem reference</em>' containment reference.
   * @see #getDataitem_reference()
   * @generated
   */
  void setDataitem_reference(dataitem_reference value);

} // stream_mime_type_attribute
