/**
 * generated by Xtext 2.13.0
 */
package io.typefox.xtext.langserver.example.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>sync policy definition</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#getsync_policy_definition()
 * @model
 * @generated
 */
public interface sync_policy_definition extends EObject
{
} // sync_policy_definition
