/**
 * generated by Xtext 2.13.0
 */
package io.typefox.xtext.langserver.example.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>target table</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.target_table#getTarget_table_target_table_name <em>Target table target table name</em>}</li>
 * </ul>
 *
 * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#gettarget_table()
 * @model
 * @generated
 */
public interface target_table extends EObject
{
  /**
   * Returns the value of the '<em><b>Target table target table name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Target table target table name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target table target table name</em>' attribute.
   * @see #setTarget_table_target_table_name(String)
   * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#gettarget_table_Target_table_target_table_name()
   * @model
   * @generated
   */
  String getTarget_table_target_table_name();

  /**
   * Sets the value of the '{@link io.typefox.xtext.langserver.example.myDsl.target_table#getTarget_table_target_table_name <em>Target table target table name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target table target table name</em>' attribute.
   * @see #getTarget_table_target_table_name()
   * @generated
   */
  void setTarget_table_target_table_name(String value);

} // target_table
