/**
 * generated by Xtext 2.13.0
 */
package io.typefox.xtext.langserver.example.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>trigger</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.trigger#getTrigger_table_name <em>Trigger table name</em>}</li>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.trigger#getTrigger_attributes <em>Trigger attributes</em>}</li>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.trigger#getObjkey_column <em>Objkey column</em>}</li>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.trigger#getTarget_table <em>Target table</em>}</li>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.trigger#getObjkey_mapping <em>Objkey mapping</em>}</li>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.trigger#getMapping_arguments <em>Mapping arguments</em>}</li>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.trigger#getGuard_function <em>Guard function</em>}</li>
 * </ul>
 *
 * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#gettrigger()
 * @model
 * @generated
 */
public interface trigger extends EObject
{
  /**
   * Returns the value of the '<em><b>Trigger table name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Trigger table name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Trigger table name</em>' attribute.
   * @see #setTrigger_table_name(String)
   * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#gettrigger_Trigger_table_name()
   * @model
   * @generated
   */
  String getTrigger_table_name();

  /**
   * Sets the value of the '{@link io.typefox.xtext.langserver.example.myDsl.trigger#getTrigger_table_name <em>Trigger table name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Trigger table name</em>' attribute.
   * @see #getTrigger_table_name()
   * @generated
   */
  void setTrigger_table_name(String value);

  /**
   * Returns the value of the '<em><b>Trigger attributes</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Trigger attributes</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Trigger attributes</em>' containment reference.
   * @see #setTrigger_attributes(trigger_attributes)
   * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#gettrigger_Trigger_attributes()
   * @model containment="true"
   * @generated
   */
  trigger_attributes getTrigger_attributes();

  /**
   * Sets the value of the '{@link io.typefox.xtext.langserver.example.myDsl.trigger#getTrigger_attributes <em>Trigger attributes</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Trigger attributes</em>' containment reference.
   * @see #getTrigger_attributes()
   * @generated
   */
  void setTrigger_attributes(trigger_attributes value);

  /**
   * Returns the value of the '<em><b>Objkey column</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Objkey column</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Objkey column</em>' containment reference.
   * @see #setObjkey_column(objkey_column)
   * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#gettrigger_Objkey_column()
   * @model containment="true"
   * @generated
   */
  objkey_column getObjkey_column();

  /**
   * Sets the value of the '{@link io.typefox.xtext.langserver.example.myDsl.trigger#getObjkey_column <em>Objkey column</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Objkey column</em>' containment reference.
   * @see #getObjkey_column()
   * @generated
   */
  void setObjkey_column(objkey_column value);

  /**
   * Returns the value of the '<em><b>Target table</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Target table</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target table</em>' containment reference.
   * @see #setTarget_table(target_table)
   * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#gettrigger_Target_table()
   * @model containment="true"
   * @generated
   */
  target_table getTarget_table();

  /**
   * Sets the value of the '{@link io.typefox.xtext.langserver.example.myDsl.trigger#getTarget_table <em>Target table</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target table</em>' containment reference.
   * @see #getTarget_table()
   * @generated
   */
  void setTarget_table(target_table value);

  /**
   * Returns the value of the '<em><b>Objkey mapping</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Objkey mapping</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Objkey mapping</em>' containment reference.
   * @see #setObjkey_mapping(objkey_mapping)
   * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#gettrigger_Objkey_mapping()
   * @model containment="true"
   * @generated
   */
  objkey_mapping getObjkey_mapping();

  /**
   * Sets the value of the '{@link io.typefox.xtext.langserver.example.myDsl.trigger#getObjkey_mapping <em>Objkey mapping</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Objkey mapping</em>' containment reference.
   * @see #getObjkey_mapping()
   * @generated
   */
  void setObjkey_mapping(objkey_mapping value);

  /**
   * Returns the value of the '<em><b>Mapping arguments</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Mapping arguments</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mapping arguments</em>' containment reference.
   * @see #setMapping_arguments(mapping_arguments)
   * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#gettrigger_Mapping_arguments()
   * @model containment="true"
   * @generated
   */
  mapping_arguments getMapping_arguments();

  /**
   * Sets the value of the '{@link io.typefox.xtext.langserver.example.myDsl.trigger#getMapping_arguments <em>Mapping arguments</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Mapping arguments</em>' containment reference.
   * @see #getMapping_arguments()
   * @generated
   */
  void setMapping_arguments(mapping_arguments value);

  /**
   * Returns the value of the '<em><b>Guard function</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Guard function</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Guard function</em>' containment reference.
   * @see #setGuard_function(guard_function)
   * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#gettrigger_Guard_function()
   * @model containment="true"
   * @generated
   */
  guard_function getGuard_function();

  /**
   * Sets the value of the '{@link io.typefox.xtext.langserver.example.myDsl.trigger#getGuard_function <em>Guard function</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Guard function</em>' containment reference.
   * @see #getGuard_function()
   * @generated
   */
  void setGuard_function(guard_function value);

} // trigger
