/**
 * generated by Xtext 2.13.0
 */
package io.typefox.xtext.langserver.example.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>type definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.type_definition#getType_definition_true_value <em>Type definition true value</em>}</li>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.type_definition#getType_definition_false_value <em>Type definition false value</em>}</li>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.type_definition#getType_definition_mime_type <em>Type definition mime type</em>}</li>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.type_definition#getType_definition_precision <em>Type definition precision</em>}</li>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.type_definition#getType_definition_scale <em>Type definition scale</em>}</li>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.type_definition#getType_definition_structure_ref <em>Type definition structure ref</em>}</li>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.type_definition#getType_definition_entity_ref <em>Type definition entity ref</em>}</li>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.type_definition#getType_definition_enumeration_ref <em>Type definition enumeration ref</em>}</li>
 *   <li>{@link io.typefox.xtext.langserver.example.myDsl.type_definition#getType_definition_enumeration_subset <em>Type definition enumeration subset</em>}</li>
 * </ul>
 *
 * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#gettype_definition()
 * @model
 * @generated
 */
public interface type_definition extends EObject
{
  /**
   * Returns the value of the '<em><b>Type definition true value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type definition true value</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type definition true value</em>' attribute.
   * @see #setType_definition_true_value(String)
   * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#gettype_definition_Type_definition_true_value()
   * @model
   * @generated
   */
  String getType_definition_true_value();

  /**
   * Sets the value of the '{@link io.typefox.xtext.langserver.example.myDsl.type_definition#getType_definition_true_value <em>Type definition true value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type definition true value</em>' attribute.
   * @see #getType_definition_true_value()
   * @generated
   */
  void setType_definition_true_value(String value);

  /**
   * Returns the value of the '<em><b>Type definition false value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type definition false value</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type definition false value</em>' attribute.
   * @see #setType_definition_false_value(String)
   * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#gettype_definition_Type_definition_false_value()
   * @model
   * @generated
   */
  String getType_definition_false_value();

  /**
   * Sets the value of the '{@link io.typefox.xtext.langserver.example.myDsl.type_definition#getType_definition_false_value <em>Type definition false value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type definition false value</em>' attribute.
   * @see #getType_definition_false_value()
   * @generated
   */
  void setType_definition_false_value(String value);

  /**
   * Returns the value of the '<em><b>Type definition mime type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type definition mime type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type definition mime type</em>' attribute.
   * @see #setType_definition_mime_type(String)
   * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#gettype_definition_Type_definition_mime_type()
   * @model
   * @generated
   */
  String getType_definition_mime_type();

  /**
   * Sets the value of the '{@link io.typefox.xtext.langserver.example.myDsl.type_definition#getType_definition_mime_type <em>Type definition mime type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type definition mime type</em>' attribute.
   * @see #getType_definition_mime_type()
   * @generated
   */
  void setType_definition_mime_type(String value);

  /**
   * Returns the value of the '<em><b>Type definition precision</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type definition precision</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type definition precision</em>' attribute.
   * @see #setType_definition_precision(int)
   * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#gettype_definition_Type_definition_precision()
   * @model
   * @generated
   */
  int getType_definition_precision();

  /**
   * Sets the value of the '{@link io.typefox.xtext.langserver.example.myDsl.type_definition#getType_definition_precision <em>Type definition precision</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type definition precision</em>' attribute.
   * @see #getType_definition_precision()
   * @generated
   */
  void setType_definition_precision(int value);

  /**
   * Returns the value of the '<em><b>Type definition scale</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type definition scale</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type definition scale</em>' attribute.
   * @see #setType_definition_scale(int)
   * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#gettype_definition_Type_definition_scale()
   * @model
   * @generated
   */
  int getType_definition_scale();

  /**
   * Sets the value of the '{@link io.typefox.xtext.langserver.example.myDsl.type_definition#getType_definition_scale <em>Type definition scale</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type definition scale</em>' attribute.
   * @see #getType_definition_scale()
   * @generated
   */
  void setType_definition_scale(int value);

  /**
   * Returns the value of the '<em><b>Type definition structure ref</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type definition structure ref</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type definition structure ref</em>' attribute.
   * @see #setType_definition_structure_ref(String)
   * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#gettype_definition_Type_definition_structure_ref()
   * @model
   * @generated
   */
  String getType_definition_structure_ref();

  /**
   * Sets the value of the '{@link io.typefox.xtext.langserver.example.myDsl.type_definition#getType_definition_structure_ref <em>Type definition structure ref</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type definition structure ref</em>' attribute.
   * @see #getType_definition_structure_ref()
   * @generated
   */
  void setType_definition_structure_ref(String value);

  /**
   * Returns the value of the '<em><b>Type definition entity ref</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type definition entity ref</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type definition entity ref</em>' attribute.
   * @see #setType_definition_entity_ref(String)
   * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#gettype_definition_Type_definition_entity_ref()
   * @model
   * @generated
   */
  String getType_definition_entity_ref();

  /**
   * Sets the value of the '{@link io.typefox.xtext.langserver.example.myDsl.type_definition#getType_definition_entity_ref <em>Type definition entity ref</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type definition entity ref</em>' attribute.
   * @see #getType_definition_entity_ref()
   * @generated
   */
  void setType_definition_entity_ref(String value);

  /**
   * Returns the value of the '<em><b>Type definition enumeration ref</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type definition enumeration ref</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type definition enumeration ref</em>' attribute.
   * @see #setType_definition_enumeration_ref(String)
   * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#gettype_definition_Type_definition_enumeration_ref()
   * @model
   * @generated
   */
  String getType_definition_enumeration_ref();

  /**
   * Sets the value of the '{@link io.typefox.xtext.langserver.example.myDsl.type_definition#getType_definition_enumeration_ref <em>Type definition enumeration ref</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type definition enumeration ref</em>' attribute.
   * @see #getType_definition_enumeration_ref()
   * @generated
   */
  void setType_definition_enumeration_ref(String value);

  /**
   * Returns the value of the '<em><b>Type definition enumeration subset</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type definition enumeration subset</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type definition enumeration subset</em>' attribute.
   * @see #setType_definition_enumeration_subset(String)
   * @see io.typefox.xtext.langserver.example.myDsl.MyDslPackage#gettype_definition_Type_definition_enumeration_subset()
   * @model
   * @generated
   */
  String getType_definition_enumeration_subset();

  /**
   * Sets the value of the '{@link io.typefox.xtext.langserver.example.myDsl.type_definition#getType_definition_enumeration_subset <em>Type definition enumeration subset</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type definition enumeration subset</em>' attribute.
   * @see #getType_definition_enumeration_subset()
   * @generated
   */
  void setType_definition_enumeration_subset(String value);

} // type_definition
